// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Main' | 'Small' // Variant
 * text?: string // Text
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "../chunks/chunk-T5SFBMCA.js";

// virtual:cards/coaching-feature
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Cards-Coaching-Feature-46aW.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["C_CH2OaKx", "jaFYQ6S9C"];
var serializationHash = "framer-IL1K5";
var variantClassNames = {
	C_CH2OaKx: "framer-v-1h0afuy",
	jaFYQ6S9C: "framer-v-2nnhdp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Main: "C_CH2OaKx",
	Small: "jaFYQ6S9C",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		nm2JPQQVq:
			text ??
			props.nm2JPQQVq ??
			"Only want Tesla tweets from Elon? Done. Follow anyone. Filter by what you actually care about.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "C_CH2OaKx",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, nm2JPQQVq, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "C_CH2OaKx",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1h0afuy",
							className,
							classNames,
						)}
						data-framer-name={"Main"}
						layoutDependency={layoutDependency}
						layoutId={"C_CH2OaKx"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								jaFYQ6S9C: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-14gx7uv"}
							data-framer-name={"Text"}
							fonts={["FS;Manrope-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"a3b3l2LiS"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-1b7bb1c4-3a89-4ec2-aee2-16abaf604d08, rgb(0, 0, 0))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={nm2JPQQVq}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									jaFYQ6S9C: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
														"--framer-font-family":
															'"Manrope", "Manrope Placeholder", sans-serif',
														"--framer-font-size": "14px",
														"--framer-line-height": "1.5em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1b7bb1c4-3a89-4ec2-aee2-16abaf604d08, rgb(0, 0, 0)))",
													}}
												>
													{"Free initial consultation"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
										"--framer-font-family":
											'"Manrope", "Manrope Placeholder", sans-serif',
										"--framer-line-height": "1.5em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-1b7bb1c4-3a89-4ec2-aee2-16abaf604d08, rgb(0, 0, 0)))",
									}}
								>
									{"Free initial consultation"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IL1K5.framer-mlcfjo, .framer-IL1K5 .framer-mlcfjo { display: block; }",
	".framer-IL1K5.framer-1h0afuy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 327px; }",
	".framer-IL1K5 .framer-14gx7uv { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
];
var FramerYv0dMYly4 = withCSS(Component, css, "framer-IL1K5");
var stdin_default = FramerYv0dMYly4;
FramerYv0dMYly4.displayName = "Cards / Coaching Feature";
FramerYv0dMYly4.defaultProps = {
	height: 72,
	width: 327,
};
addPropertyControls(FramerYv0dMYly4, {
	variant: {
		options: ["C_CH2OaKx", "jaFYQ6S9C"],
		optionTitles: ["Main", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	nm2JPQQVq: {
		defaultValue:
			"Only want Tesla tweets from Elon? Done. Follow anyone. Filter by what you actually care about.",
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerYv0dMYly4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Manrope",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2TYFCBHUANEXS6QGR5EQDUNAFH6LSWM3/AYNOU3VEA4LRTDNKJQUFNVNUTYSGOUOP/UXO4O7K2G3HI3D2VKD7UXVJVJD26P4BQ.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/coaching-feature
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "C_CH2OaKx",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders CoachingFeatureFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var coaching_feature_default = ComponentWithRoot;
export { coaching_feature_default as default };
