// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Medium' | 'Small' // Variant
 * logo?: {src: string, srcSet?: string, alt?: string} // logo
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "../chunks/chunk-T5SFBMCA.js";

// virtual:elements/logo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Elements-Logo-Wl9v.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["iZOhxWMSl", "BaGzjVQQw", "aplz6GgEY"];
var serializationHash = "framer-e2yEq";
var variantClassNames = {
	aplz6GgEY: "framer-v-18qbxod",
	BaGzjVQQw: "framer-v-78j42u",
	iZOhxWMSl: "framer-v-1h94pgx",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "iZOhxWMSl",
	Medium: "BaGzjVQQw",
	Small: "aplz6GgEY",
};
var getProps = ({ height, id, logo, width, ...props }) => {
	return {
		...props,
		PIwNgm_lj: logo ??
			props.PIwNgm_lj ?? {
				alt: "logo",
				pixelHeight: 162,
				pixelWidth: 428,
				src: "https://framerusercontent.com/images/on7xUpJ1SM94eAeiyf04v5F4rjQ.png",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "iZOhxWMSl",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, PIwNgm_lj, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iZOhxWMSl",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1h94pgx",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"iZOhxWMSl"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								aplz6GgEY: {
									"data-framer-name": "Small",
								},
								BaGzjVQQw: {
									"data-framer-name": "Medium",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link
							motionChild={true}
							nodeId={"exc087fnF"}
							scopeId={"MtpmeeFni"}
							{...addPropertyOverrides(
								{
									BaGzjVQQw: {
										href: {
											webPageId: "augiA20Il",
										},
										openInNewTab: false,
										smoothScroll: true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 460,
									intrinsicWidth: 2751,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 +
												((componentViewport?.height || 46) -
													0 -
													((componentViewport?.height || 46) - 0) * 1) /
													2),
									),
									pixelHeight: 162,
									pixelWidth: 428,
									sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
									...toResponsiveImage(PIwNgm_lj),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-2h926m framer-1hgyrav"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"exc087fnF"}
								{...addPropertyOverrides(
									{
										aplz6GgEY: {
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 460,
												intrinsicWidth: 2751,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 31) -
																0 -
																((componentViewport?.height || 31) - 0) * 1) /
																2),
												),
												pixelHeight: 162,
												pixelWidth: 428,
												sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
												...toResponsiveImage(PIwNgm_lj),
												...{
													positionX: "center",
													positionY: "center",
												},
											},
										},
										BaGzjVQQw: {
											as: "a",
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 460,
												intrinsicWidth: 2751,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 36) -
																0 -
																((componentViewport?.height || 36) - 0) * 1) /
																2),
												),
												pixelHeight: 162,
												pixelWidth: 428,
												sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
												...toResponsiveImage(PIwNgm_lj),
												...{
													positionX: "left",
													positionY: "center",
												},
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</Link>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-e2yEq.framer-1hgyrav, .framer-e2yEq .framer-1hgyrav { display: block; }",
	".framer-e2yEq.framer-1h94pgx { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 46px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 169px; }",
	".framer-e2yEq .framer-2h926m { flex: 1 0 0px; height: 100%; overflow: visible; position: relative; width: 1px; }",
	".framer-e2yEq.framer-v-78j42u.framer-1h94pgx { height: 36px; width: 113px; }",
	".framer-e2yEq.framer-v-78j42u .framer-2h926m { order: 0; text-decoration: none; }",
	".framer-e2yEq.framer-v-18qbxod.framer-1h94pgx { height: 31px; width: 110px; }",
	".framer-e2yEq.framer-v-18qbxod .framer-2h926m { order: 0; }",
];
var FramerMtpmeeFni = withCSS(Component, css, "framer-e2yEq");
var stdin_default = FramerMtpmeeFni;
FramerMtpmeeFni.displayName = "Elements / Logo";
FramerMtpmeeFni.defaultProps = {
	height: 46,
	width: 169,
};
addPropertyControls(FramerMtpmeeFni, {
	variant: {
		options: ["iZOhxWMSl", "BaGzjVQQw", "aplz6GgEY"],
		optionTitles: ["Default", "Medium", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	PIwNgm_lj: {
		__defaultAssetReference:
			"data:framer/asset-reference,on7xUpJ1SM94eAeiyf04v5F4rjQ.png?originalFilename=Group+c.png&preferredSize=auto",
		__vekterDefault: {
			alt: "logo",
			assetReference:
				"data:framer/asset-reference,on7xUpJ1SM94eAeiyf04v5F4rjQ.png?originalFilename=Group+c.png&preferredSize=auto",
		},
		title: "logo",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerMtpmeeFni,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:elements/logo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders LogoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var logo_default = ComponentWithRoot;
export { logo_default as default };
