// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'PrimaryButton' | 'NavBarButton' | 'NavBarMobile' | 'DownloadButton' // Variant
 * title?: string // Title
 * link?: string // Link
 * tap?: Function // Tap
 * textColor?: string // TextColor
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "../chunks/chunk-T5SFBMCA.js";

// virtual:buttons/navigation-bar-button-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Buttons-Navigation-Bar-Button-2-Ap0S.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	h3edcce0z: {
		hover: true,
	},
	KaWdGN1UP: {
		hover: true,
	},
	wYMukC0Ft: {
		hover: true,
	},
};
var cycleOrder = ["h3edcce0z", "KaWdGN1UP", "oJDoJijin", "wYMukC0Ft"];
var serializationHash = "framer-Q0J8M";
var variantClassNames = {
	h3edcce0z: "framer-v-1amv7wg",
	KaWdGN1UP: "framer-v-14iqav7",
	oJDoJijin: "framer-v-1vzm74g",
	wYMukC0Ft: "framer-v-17zx5ld",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transformTemplate2 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	DownloadButton: "wYMukC0Ft",
	NavBarButton: "KaWdGN1UP",
	NavBarMobile: "oJDoJijin",
	PrimaryButton: "h3edcce0z",
};
var getProps = ({
	height,
	id,
	link,
	tap,
	textColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		B0eTuUnrS: link ?? props.B0eTuUnrS,
		FOxcLjTdx: title ?? props.FOxcLjTdx ?? "Button",
		jkE7sM56V:
			textColor ??
			props.jkE7sM56V ??
			"var(--token-545afc82-d790-4647-bdd0-17dca164eab2, rgb(11, 11, 11))",
		QIrXjwYb4: tap ?? props.QIrXjwYb4,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "h3edcce0z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		FOxcLjTdx,
		B0eTuUnrS,
		QIrXjwYb4,
		jkE7sM56V,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "h3edcce0z",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1az1o4n = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (QIrXjwYb4) {
			const res = await QIrXjwYb4(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "oJDoJijin") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={B0eTuUnrS}
						motionChild={true}
						nodeId={"h3edcce0z"}
						openInNewTab={false}
						scopeId={"FXUUlEhU8"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1amv7wg", className, classNames)} framer-fwu8ew`}
							data-framer-name={"PrimaryButton"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"h3edcce0z"}
							onTap={onTap1az1o4n}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								boxShadow: "none",
								...style,
							}}
							variants={{
								"h3edcce0z-hover": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									boxShadow: "none",
								},
								"KaWdGN1UP-hover": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									boxShadow: "none",
								},
								wYMukC0Ft: {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-b475daa1-123e-4ac4-9203-afa2fe736f56, rgb(255, 255, 255))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor:
										"var(--token-de34b1db-c617-47fd-9a6d-ca7f94a49e32, rgb(255, 224, 224))",
									borderBottomLeftRadius: 11,
									borderBottomRightRadius: 11,
									borderTopLeftRadius: 11,
									borderTopRightRadius: 11,
									boxShadow:
										"0px 0.6021873017743928px 1.5656869846134214px -1.25px rgba(255, 255, 255, 0.72), 0px 2.288533303243457px 5.950186588432988px -2.5px rgba(255, 255, 255, 0.64), 0px 10px 26px -3.75px rgba(255, 255, 255, 0.25)",
								},
							}}
							{...addPropertyOverrides(
								{
									"h3edcce0z-hover": {
										"data-framer-name": void 0,
									},
									"KaWdGN1UP-hover": {
										"data-framer-name": void 0,
									},
									"wYMukC0Ft-hover": {
										"data-framer-name": void 0,
									},
									KaWdGN1UP: {
										"data-framer-name": "NavBarButton",
									},
									oJDoJijin: {
										"data-framer-name": "NavBarMobile",
									},
									wYMukC0Ft: {
										"data-border": true,
										"data-framer-name": "DownloadButton",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1g7vgei"}
								data-framer-name={"Title1"}
								fonts={["FS;Satoshi-medium", "FS;Satoshi-bold"]}
								layoutDependency={layoutDependency}
								layoutId={"T0KYiA1SQ"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-jkE7sM56V-FXUUlEhU8)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-jkE7sM56V-FXUUlEhU8": jkE7sM56V,
								}}
								text={FOxcLjTdx}
								transformTemplate={transformTemplate1}
								variants={{
									oJDoJijin: {
										"--extracted-r6o4lv":
											"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(0, 0, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"h3edcce0z-hover": {
											transformTemplate: transformTemplate2,
										},
										"wYMukC0Ft-hover": {
											transformTemplate: transformTemplate2,
										},
										oJDoJijin: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(0, 0, 0)))",
														}}
													>
														<motion.strong>{"Button"}</motion.strong>
													</motion.p>
												</React.Fragment>
											),
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
											"--framer-font-family":
												'"Satoshi", "Satoshi Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-jkE7sM56V-FXUUlEhU8))",
										}}
									>
										<motion.strong>{"Button"}</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1t89vrb"}
									data-framer-name={"Title2"}
									fonts={["FS;Satoshi-medium", "FS;Satoshi-bold"]}
									layoutDependency={layoutDependency}
									layoutId={"K3NSp8IkT"}
									style={{
										"--extracted-r6o4lv":
											"var(--variable-reference-jkE7sM56V-FXUUlEhU8)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-jkE7sM56V-FXUUlEhU8": jkE7sM56V,
									}}
									text={FOxcLjTdx}
									transformTemplate={transformTemplate2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"h3edcce0z-hover": {
												transformTemplate: transformTemplate1,
											},
											"wYMukC0Ft-hover": {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-weight": "500",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--variable-reference-jkE7sM56V-FXUUlEhU8))",
											}}
										>
											<motion.strong>{"Button"}</motion.strong>
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Q0J8M.framer-fwu8ew, .framer-Q0J8M .framer-fwu8ew { display: block; }",
	".framer-Q0J8M.framer-1amv7wg { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 100px; }",
	".framer-Q0J8M .framer-1g7vgei { flex: none; height: auto; left: 50%; position: absolute; top: 49%; white-space: pre; width: auto; z-index: 1; }",
	".framer-Q0J8M .framer-1t89vrb { bottom: -22px; flex: none; height: auto; left: 49%; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-Q0J8M.framer-v-1vzm74g.framer-1amv7wg { align-content: flex-start; align-items: flex-start; height: min-content; width: min-content; }",
	".framer-Q0J8M.framer-v-1vzm74g .framer-1g7vgei { left: unset; position: relative; top: unset; }",
	".framer-Q0J8M.framer-v-17zx5ld.framer-1amv7wg { will-change: var(--framer-will-change-override, transform); }",
	".framer-Q0J8M.framer-v-1amv7wg.hover .framer-1g7vgei { left: 49%; top: -22px; }",
	".framer-Q0J8M.framer-v-1amv7wg.hover .framer-1t89vrb { bottom: unset; top: 51%; }",
	".framer-Q0J8M.framer-v-17zx5ld.hover .framer-1g7vgei { left: 49%; top: -24px; }",
	".framer-Q0J8M.framer-v-17zx5ld.hover .framer-1t89vrb { bottom: unset; left: 49%; top: 48%; }",
	'.framer-Q0J8M[data-border="true"]::after, .framer-Q0J8M [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFXUUlEhU8 = withCSS(Component, css, "framer-Q0J8M");
var stdin_default = FramerFXUUlEhU8;
FramerFXUUlEhU8.displayName = "Buttons/ Navigation Bar Button 2";
FramerFXUUlEhU8.defaultProps = {
	height: 40,
	width: 100,
};
addPropertyControls(FramerFXUUlEhU8, {
	variant: {
		options: ["h3edcce0z", "KaWdGN1UP", "oJDoJijin", "wYMukC0Ft"],
		optionTitles: [
			"PrimaryButton",
			"NavBarButton",
			"NavBarMobile",
			"DownloadButton",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	FOxcLjTdx: {
		defaultValue: "Button",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	B0eTuUnrS: {
		title: "Link",
		type: ControlType.Link,
	},
	QIrXjwYb4: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
	jkE7sM56V: {
		defaultValue:
			"var(--token-545afc82-d790-4647-bdd0-17dca164eab2, rgb(11, 11, 11))",
		title: "TextColor",
		type: ControlType.Color,
	},
});
addFonts(
	FramerFXUUlEhU8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
					weight: "700",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons/navigation-bar-button-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders NavigationBarButton2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var navigation_bar_button_2_default = ComponentWithRoot;
export { navigation_bar_button_2_default as default };
