// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'First' | 'Third' // Variant
 * direction?: 'Horizontal' | 'Vertical' // Direction
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:01
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/01-FaMO.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["aDpt9caQQ", "dV7a4So8L"];
var serializationHash = "framer-vfEbQ";
var variantClassNames = {
	aDpt9caQQ: "framer-v-1bml1vf",
	dV7a4So8L: "framer-v-1sso7a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	Horizontal: "row",
	Vertical: "column",
};
var humanReadableVariantMap = {
	First: "aDpt9caQQ",
	Third: "dV7a4So8L",
};
var getProps = ({ direction, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "aDpt9caQQ",
		WH7nHWRzl:
			humanReadableEnumMap[direction] ?? direction ?? props.WH7nHWRzl ?? "row",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, WH7nHWRzl, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aDpt9caQQ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1bml1vf",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"First"}
						layoutDependency={layoutDependency}
						layoutId={"aDpt9caQQ"}
						ref={refBinding}
						style={{
							"--1iw0kpf": WH7nHWRzl,
							"--border-bottom-width": "1px",
							"--border-color": "rgb(232, 232, 232)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgb(246, 246, 246)",
							boxShadow: "inset 0px 2px 0px 0px rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								dV7a4So8L: {
									"data-framer-name": "Third",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vfEbQ.framer-1972dmz, .framer-vfEbQ .framer-1972dmz { display: block; }",
	".framer-vfEbQ.framer-1bml1vf { align-content: center; align-items: center; display: flex; flex-direction: var(--1iw0kpf); flex-wrap: nowrap; gap: 10px; height: 320px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 900px; }",
	'.framer-vfEbQ[data-border="true"]::after, .framer-vfEbQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerphKGgvbrn = withCSS(Component, css, "framer-vfEbQ");
var stdin_default = FramerphKGgvbrn;
FramerphKGgvbrn.displayName = "01";
FramerphKGgvbrn.defaultProps = {
	height: 320,
	width: 900,
};
addPropertyControls(FramerphKGgvbrn, {
	variant: {
		options: ["aDpt9caQQ", "dV7a4So8L"],
		optionTitles: ["First", "Third"],
		title: "Variant",
		type: ControlType.Enum,
	},
	WH7nHWRzl: {
		defaultValue: "row",
		displaySegmentedControl: true,
		optionIcons: ["direction-horizontal", "direction-vertical"],
		options: ["row", "column"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Direction",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerphKGgvbrn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:01
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders 01FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var __default = ComponentWithRoot;
export { __default as default };
