// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * click?: Function // Click
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:arrow
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Arrow-zLo7.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	HQ1OgiKO2: {
		pressed: true,
	},
};
var serializationHash = "framer-PyKwS";
var variantClassNames = {
	HQ1OgiKO2: "framer-v-ckrdnm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		gXj_EngQX: click ?? props.gXj_EngQX,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, gXj_EngQX, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "HQ1OgiKO2",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapsz09t2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (gXj_EngQX) {
			const res = await gXj_EngQX(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ckrdnm",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"HQ1OgiKO2"}
						onTap={onTapsz09t2}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(0, 0, 0)",
							borderBottomLeftRadius: 414,
							borderBottomRightRadius: 414,
							borderTopLeftRadius: 414,
							borderTopRightRadius: 414,
							...style,
						}}
						variants={{
							"HQ1OgiKO2-pressed": {
								backgroundColor: "rgba(0, 0, 0, 0.7)",
							},
						}}
						{...addPropertyOverrides(
							{
								"HQ1OgiKO2-pressed": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							className={"framer-rntqfg"}
							data-framer-name={"Chevron"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"JkA2MC7r8"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 8.25 4.5 L 15.75 12 L 8.25 19.5" fill="transparent" stroke-width="2" stroke="var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))" stroke-linecap="round" stroke-linejoin="round"></path></svg>'
							}
							svgContentId={9243947916}
							withExternalLayout={true}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PyKwS.framer-16q0gmi, .framer-PyKwS .framer-16q0gmi { display: block; }",
	".framer-PyKwS.framer-ckrdnm { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-PyKwS .framer-rntqfg { flex: none; height: 24px; position: relative; width: 24px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PyKwS.framer-ckrdnm { gap: 0px; } .framer-PyKwS.framer-ckrdnm > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-PyKwS.framer-ckrdnm > :first-child { margin-left: 0px; } .framer-PyKwS.framer-ckrdnm > :last-child { margin-right: 0px; } }",
];
var FramercHyKLlYLL = withCSS(Component, css, "framer-PyKwS");
var stdin_default = FramercHyKLlYLL;
FramercHyKLlYLL.displayName = "Arrow";
FramercHyKLlYLL.defaultProps = {
	height: 44,
	width: 44,
};
addPropertyControls(FramercHyKLlYLL, {
	gXj_EngQX: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramercHyKLlYLL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:arrow
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders ArrowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var arrow_default = ComponentWithRoot;
export { arrow_default as default };
