// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
	stdin_default,
} from "./chunks/chunk-XLXKYAVK.js";
import { className, css, fonts } from "./chunks/chunk-PU7BSL5Q.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:background
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/background-80yS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonsButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var ImageWithFX = withFX(Image);
var serializationHash = "framer-xqNAT";
var variantClassNames = {
	sdd07EdxS: "framer-v-1xxwjwe",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition2 = {
	delay: 0,
	duration: 1.8,
	ease: [0.67, 0.33, 0.23, 1.02],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.7,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 1.6,
	ease: [0.67, 0.33, 0.23, 1.02],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation3 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1.4,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition4 = {
	delay: 0.05,
	duration: 0.45,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var textEffect = {
	effect: animation3,
	repeat: false,
	startDelay: 0,
	tokenization: "character",
	transition: transition4,
	trigger: "onMount",
	type: "appear",
};
var animation4 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition5 = {
	bounce: 0,
	delay: 0.01,
	duration: 0.2,
	type: "spring",
};
var textEffect1 = {
	effect: animation4,
	startDelay: 1.5,
	tokenization: "character",
	transition: transition5,
	trigger: "onMount",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "sdd07EdxS",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<ImageWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__adjustPosition={false}
						__framer__offset={0}
						__framer__parallaxTransformEnabled={true}
						__framer__speed={80}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 2735,
							intrinsicWidth: 2191,
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 4403,
							pixelWidth: 1920,
							positionX: "center",
							positionY: "top",
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=4096",
							srcSet:
								"https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=2048 893w,https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png 1920w",
						}}
						className={cx(
							scopingClassNames,
							"framer-1xxwjwe",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"sdd07EdxS"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 958,
								),
								pixelHeight: 661,
								pixelWidth: 1080,
								sizes: "263px",
								src: "https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png",
								srcSet:
									"https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png 1080w",
							}}
							className={"framer-1huniq5"}
							layoutDependency={layoutDependency}
							layoutId={"dtZpANgkj"}
						/>
						<ComponentViewportProvider
							height={52}
							y={(componentViewport?.y || 0) + 543}
						>
							<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={100}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-18dm7lu-container"}
								data-framer-appear-id={"18dm7lu"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"IYdljxCcJ-container"}
								nodeId={"IYdljxCcJ"}
								optimized={true}
								rendersWithMotion={true}
								scopeId={"pcuK4Mnm2"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									cRoeZpcrs: "Join The Waitlist - Get Early Access",
									FsefAOOPs:
										"var(--token-d49ce14e-f5dc-463a-9b8d-4f0e772df7f1, rgb(255, 255, 255))",
									height: "100%",
									id: "IYdljxCcJ",
									layoutId: "IYdljxCcJ",
									SM93ZbT4W: true,
									variant: "ElkbJxbcB",
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
						</ComponentViewportProvider>
						<RichTextWithFXWithOptimizedAppearEffect
							__framer__adjustPosition={false}
							__framer__offset={0}
							__framer__parallaxTransformEnabled={true}
							__framer__speed={100}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation2}
							className={"framer-1ilmqqm"}
							data-framer-appear-id={"1ilmqqm"}
							effect={textEffect}
							fonts={["Inter"]}
							initial={animation1}
							layoutDependency={layoutDependency}
							layoutId={"yszxu4bpb"}
							optimized={true}
							style={{
								"--extracted-gdpscs":
									"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									className={"framer-styles-preset-1jo3glk"}
									data-styles-preset={"enXnUuyN7"}
									style={{
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-gdpscs, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11)))",
									}}
								>
									{"Control your X feed."}
									<motion.br />
									{"No more noise. Just signal."}
								</motion.h1>
							</React.Fragment>
						</RichTextWithFXWithOptimizedAppearEffect>
						<RichTextWithFXWithOptimizedAppearEffect
							__framer__adjustPosition={false}
							__framer__offset={0}
							__framer__parallaxTransformEnabled={true}
							__framer__speed={100}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation2}
							className={"framer-frtxnb"}
							data-framer-appear-id={"frtxnb"}
							effect={textEffect1}
							fonts={["Inter"]}
							initial={animation1}
							layoutDependency={layoutDependency}
							layoutId={"MfY8AJTFJ"}
							optimized={true}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h3
									className={"framer-styles-preset-1tsd54f"}
									data-styles-preset={"DhsVO3ura"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{
										"Follow anyone. See only what matters - from a list that you control."
									}
								</motion.h3>
							</React.Fragment>
						</RichTextWithFXWithOptimizedAppearEffect>
					</ImageWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xqNAT.framer-176dcq2, .framer-xqNAT .framer-176dcq2 { display: block; }",
	".framer-xqNAT.framer-1xxwjwe { height: 3092px; overflow: visible; position: relative; width: 1440px; }",
	".framer-xqNAT .framer-1huniq5 { flex: none; height: 115px; left: calc(50.00000000000002% - 263px / 2); position: absolute; top: 958px; width: 263px; }",
	".framer-xqNAT .framer-18dm7lu-container { flex: none; height: auto; left: 50%; position: absolute; top: 543px; width: auto; z-index: 3; }",
	".framer-xqNAT .framer-1ilmqqm { flex: none; height: auto; left: 50%; position: absolute; top: 274px; white-space: pre; width: auto; z-index: 1; }",
	".framer-xqNAT .framer-frtxnb { flex: none; height: auto; left: 50%; position: absolute; top: 451px; white-space: pre; width: auto; z-index: 1; }",
	...css2,
	...css,
];
var FramerpcuK4Mnm2 = withCSS(Component, css3, "framer-xqNAT");
var stdin_default2 = FramerpcuK4Mnm2;
FramerpcuK4Mnm2.displayName = "background";
FramerpcuK4Mnm2.defaultProps = {
	height: 3092,
	width: 1440,
};
addFonts(
	FramerpcuK4Mnm2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonsButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:background
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders BackgroundFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var background_default = ComponentWithRoot;
export { background_default as default };
