// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'DarkBadge' | 'LightBadge' // Variant
 * title?: string // Title
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:badge
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Badge-7vot.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["rxqHjK6oR", "SW2rjKtBv"];
var serializationHash = "framer-6wl8l";
var variantClassNames = {
	rxqHjK6oR: "framer-v-y2v60s",
	SW2rjKtBv: "framer-v-1am6oah",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	DarkBadge: "rxqHjK6oR",
	LightBadge: "SW2rjKtBv",
};
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		geY96KGtC: title ?? props.geY96KGtC ?? "Section",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rxqHjK6oR",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, geY96KGtC, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rxqHjK6oR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-y2v60s",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"DarkBadge"}
						layoutDependency={layoutDependency}
						layoutId={"rxqHjK6oR"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-b475daa1-123e-4ac4-9203-afa2fe736f56, rgb(255, 255, 255))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(7px)",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							WebkitBackdropFilter: "blur(7px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								SW2rjKtBv: {
									"data-framer-name": "LightBadge",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tgjwqc"}
							data-framer-name={"Background"}
							layoutDependency={layoutDependency}
							layoutId={"QeD3XoSzn"}
							style={{
								backgroundColor:
									"var(--token-de34b1db-c617-47fd-9a6d-ca7f94a49e32, rgb(255, 224, 224))",
								opacity: 0.4,
							}}
							variants={{
								SW2rjKtBv: {
									backgroundColor:
										"var(--token-b475daa1-123e-4ac4-9203-afa2fe736f56, rgb(255, 255, 255))",
									opacity: 0.8,
								},
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1dn5d43"}
							data-framer-name={"Label"}
							fonts={["FS;Satoshi-bold"]}
							layoutDependency={layoutDependency}
							layoutId={"kBT0AfV08"}
							style={{
								"--extracted-1lwpl3i":
									"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(0, 0, 0))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={geY96KGtC}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h5
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1ib2xk",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "13px",
										"--framer-font-weight": "700",
										"--framer-letter-spacing": "0.04em",
										"--framer-line-height": "1.4em",
										"--framer-text-color":
											"var(--extracted-1lwpl3i, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(0, 0, 0)))",
										"--framer-text-transform": "uppercase",
									}}
								>
									{"Section"}
								</motion.h5>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6wl8l.framer-22sw6z, .framer-6wl8l .framer-22sw6z { display: block; }",
	".framer-6wl8l.framer-y2v60s { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 24px 8px 24px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-6wl8l .framer-1tgjwqc { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	".framer-6wl8l .framer-1dn5d43 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6wl8l.framer-y2v60s { gap: 0px; } .framer-6wl8l.framer-y2v60s > * { margin: 0px; margin-left: calc(3px / 2); margin-right: calc(3px / 2); } .framer-6wl8l.framer-y2v60s > :first-child { margin-left: 0px; } .framer-6wl8l.framer-y2v60s > :last-child { margin-right: 0px; } }",
	'.framer-6wl8l[data-border="true"]::after, .framer-6wl8l [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerhc0Dm4hRv = withCSS(Component, css, "framer-6wl8l");
var stdin_default = Framerhc0Dm4hRv;
Framerhc0Dm4hRv.displayName = "Badge";
Framerhc0Dm4hRv.defaultProps = {
	height: 34,
	width: 108,
};
addPropertyControls(Framerhc0Dm4hRv, {
	variant: {
		options: ["rxqHjK6oR", "SW2rjKtBv"],
		optionTitles: ["DarkBadge", "LightBadge"],
		title: "Variant",
		type: ControlType.Enum,
	},
	geY96KGtC: {
		defaultValue: "Section",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	Framerhc0Dm4hRv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
					weight: "700",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:badge
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders BadgeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var badge_default = ComponentWithRoot;
export { badge_default as default };
