// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * label?: string // Label
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { RollingText } from "./chunks/chunk-PO5D4RYP.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:button-rolling
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Button-Rolling-fZAl.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Link,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RollingTextFonts = getFonts(RollingText);
var serializationHash = "framer-wYxdt";
var variantClassNames = {
	UV5dD4YDy: "framer-v-1p4kx1z",
};
var transition1 = {
	delay: 0,
	duration: 0.5,
	ease: [0.82, 0.08, 0.29, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, label, link, width, ...props }) => {
	return {
		...props,
		En8F1FnWK: label ?? props.En8F1FnWK ?? "Get started",
		tenuaCvri: link ?? props.tenuaCvri,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		tenuaCvri,
		En8F1FnWK,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "UV5dD4YDy",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={tenuaCvri}
						motionChild={true}
						nodeId={"UV5dD4YDy"}
						scopeId={"V6XpBHGQC"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1p4kx1z", className, classNames)} framer-nmezl6`}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"UV5dD4YDy"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								...style,
							}}
						>
							<motion.div
								className={"framer-1h4jzhq"}
								data-border={true}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"z_YCrUEw6"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(255, 255, 255, 0)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgb(255, 255, 255)",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-dqep14-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"hgyIfQrhj-container"}
										nodeId={"hgyIfQrhj"}
										rendersWithMotion={true}
										scopeId={"V6XpBHGQC"}
									>
										<RollingText
											color={"rgb(255, 255, 255)"}
											font={{
												fontFamily: '"Inter", "Inter Placeholder", sans-serif',
												fontSize: "16px",
												fontStyle: "normal",
												fontWeight: 600,
												letterSpacing: "0px",
												lineHeight: "1.2em",
											}}
											height={"100%"}
											id={"hgyIfQrhj"}
											layoutId={"hgyIfQrhj"}
											padding={"12px 18px 12px 18px"}
											reverse={false}
											stagger={35}
											tag={"p"}
											text={En8F1FnWK}
											textTransform={"none"}
											transition={{
												delay: 0,
												duration: 0.5,
												ease: [0.82, 0.08, 0.29, 1],
												type: "tween",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wYxdt.framer-nmezl6, .framer-wYxdt .framer-nmezl6 { display: block; }",
	".framer-wYxdt.framer-1p4kx1z { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-wYxdt .framer-1h4jzhq { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: auto; will-change: var(--framer-will-change-override, transform); }",
	".framer-wYxdt .framer-dqep14-container { flex: none; height: auto; mix-blend-mode: difference; position: relative; width: auto; }",
	'.framer-wYxdt[data-border="true"]::after, .framer-wYxdt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerV6XpBHGQC = withCSS(Component, css, "framer-wYxdt");
var stdin_default = FramerV6XpBHGQC;
FramerV6XpBHGQC.displayName = "Button Rolling";
FramerV6XpBHGQC.defaultProps = {
	height: 43,
	width: 122,
};
addPropertyControls(FramerV6XpBHGQC, {
	tenuaCvri: {
		title: "Link",
		type: ControlType.Link,
	},
	En8F1FnWK: {
		defaultValue: "Get started",
		title: "Label",
		type: ControlType.String,
	},
});
addFonts(
	FramerV6XpBHGQC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
		...RollingTextFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-rolling
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders ButtonRollingFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_rolling_default = ComponentWithRoot;
export { button_rolling_default as default };
