// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { stdin_default } from "./chunks/chunk-WUOXNKG3.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:faq-s-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Faq-s-section-c2X1.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	RichText,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/OQU9Bx3ywsy6ANnqwoZm/yIg3MZ0GDA1DMSp467c9/m3r4k9yWn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ElementsFAQItemFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["zmrpr3jwr", "kYaPHD6hb"];
var serializationHash = "framer-BILSQ";
var variantClassNames = {
	kYaPHD6hb: "framer-v-d2h6e5",
	zmrpr3jwr: "framer-v-1l9tw9m",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 60,
};
var transition3 = {
	bounce: 0.2,
	delay: 0.1,
	duration: 0.6,
	type: "spring",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 60,
};
var transition4 = {
	bounce: 0.2,
	delay: 0.2,
	duration: 0.6,
	type: "spring",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 60,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "zmrpr3jwr",
	mobile: "kYaPHD6hb",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zmrpr3jwr",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zmrpr3jwr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1l9tw9m",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"zmrpr3jwr"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								kYaPHD6hb: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 304) - 0 - 304) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-bp8oag-container"}
								layoutDependency={layoutDependency}
								layoutId={"bXzxe6bpl-container"}
								nodeId={"bXzxe6bpl"}
								rendersWithMotion={true}
								scopeId={"m3r4k9yWn"}
								{...addPropertyOverrides(
									{
										kYaPHD6hb: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Filtr lets you customize what you see on X (formerly Twitter). Want only Elon\u2019s takes on Tesla and none of his ",
									height: "100%",
									id: "bXzxe6bpl",
									layoutId: "bXzxe6bpl",
									pNqA5B2sU: "What exactly does Filtr do?",
									style: {
										width: "100%",
									},
									variant: "ragvqzOLz",
									width: "100%",
									...addPropertyOverrides(
										{
											kYaPHD6hb: {
												variant: "A9196_NL3",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 304) - 0 - 304) / 2 + 48 + 16)
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation2}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-m6akjf-container"}
								layoutDependency={layoutDependency}
								layoutId={"gJRVC13WQ-container"}
								nodeId={"gJRVC13WQ"}
								rendersWithMotion={true}
								scopeId={"m3r4k9yWn"}
								{...addPropertyOverrides(
									{
										kYaPHD6hb: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Lists and mute filters are blunt tools. Filtr gives you fine-grained control \u2014 you decide what topics you want from specific accounts. Think of it like a smart assistant curating your feed, not just hiding noise.",
									height: "100%",
									id: "gJRVC13WQ",
									layoutId: "gJRVC13WQ",
									pNqA5B2sU:
										"How is this different from X Lists or Mute filters?",
									style: {
										width: "100%",
									},
									variant: "ragvqzOLz",
									width: "100%",
									...addPropertyOverrides(
										{
											kYaPHD6hb: {
												pNqA5B2sU:
													"How is this different from X Lists filters?",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 304) - 0 - 304) / 2 + 96 + 32)
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation2}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-emktf7-container"}
								layoutDependency={layoutDependency}
								layoutId={"uUxxEfIia-container"}
								nodeId={"uUxxEfIia"}
								rendersWithMotion={true}
								scopeId={"m3r4k9yWn"}
								{...addPropertyOverrides(
									{
										kYaPHD6hb: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"We use advanced AI models to understand tweet content in context \u2014 including slang, sarcasm, and thread replies. It\u2019s built specifically for the fast, chaotic style of crypto/X.",
									height: "100%",
									id: "uUxxEfIia",
									layoutId: "uUxxEfIia",
									pNqA5B2sU: "How does Filtr know what a tweet is about?",
									style: {
										width: "100%",
									},
									variant: "ragvqzOLz",
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 304) - 0 - 304) / 2 + 144 + 48)
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition4,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1um8go4-container"}
								layoutDependency={layoutDependency}
								layoutId={"HadX8lhMY-container"}
								nodeId={"HadX8lhMY"}
								rendersWithMotion={true}
								scopeId={"m3r4k9yWn"}
								{...addPropertyOverrides(
									{
										kYaPHD6hb: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"You\u2019re in control. You can adjust or override filters anytime. We\u2019re also constantly improving based on real user feedback \u2014 this is made for power users like you.",
									height: "100%",
									id: "HadX8lhMY",
									layoutId: "HadX8lhMY",
									pNqA5B2sU: "Can I trust the AI to get it right?",
									style: {
										width: "100%",
									},
									variant: "ragvqzOLz",
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 304) - 0 - 304) / 2 + 192 + 64)
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition4,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-14ruhp3-container"}
								layoutDependency={layoutDependency}
								layoutId={"YywzAapPV-container"}
								nodeId={"YywzAapPV"}
								rendersWithMotion={true}
								scopeId={"m3r4k9yWn"}
								{...addPropertyOverrides(
									{
										kYaPHD6hb: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"No - All you need to do is enter your X username into our platform, and Filtr does the rest.",
									height: "100%",
									id: "YywzAapPV",
									layoutId: "YywzAapPV",
									pNqA5B2sU: "Do you need my X (Twitter) login?",
									style: {
										width: "100%",
									},
									variant: "ragvqzOLz",
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BILSQ.framer-vrw01z, .framer-BILSQ .framer-vrw01z { display: block; }",
	".framer-BILSQ.framer-1l9tw9m { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 467px; }",
	".framer-BILSQ .framer-bp8oag-container, .framer-BILSQ .framer-m6akjf-container, .framer-BILSQ .framer-emktf7-container, .framer-BILSQ .framer-1um8go4-container, .framer-BILSQ .framer-14ruhp3-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-BILSQ.framer-v-d2h6e5.framer-1l9tw9m { width: 508px; }",
];
var Framerm3r4k9yWn = withCSS(Component, css, "framer-BILSQ");
var stdin_default2 = Framerm3r4k9yWn;
Framerm3r4k9yWn.displayName = "Cards/FAQ";
Framerm3r4k9yWn.defaultProps = {
	height: 304,
	width: 467,
};
addPropertyControls(Framerm3r4k9yWn, {
	variant: {
		options: ["zmrpr3jwr", "kYaPHD6hb"],
		optionTitles: ["Default", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerm3r4k9yWn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ElementsFAQItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Faq-s-section-c2X1.js
var CardsFAQFonts = getFonts2(stdin_default2);
var cycleOrder2 = ["XCrIpY8RT", "bDwpUZwbz", "sQyJ43R8p"];
var serializationHash2 = "framer-hLqW0";
var variantClassNames2 = {
	bDwpUZwbz: "framer-v-115a22f",
	sQyJ43R8p: "framer-v-1ro9jv2",
	XCrIpY8RT: "framer-v-2tptxy",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation4 = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 5,
};
var transition22 = {
	damping: 100,
	delay: 0.05,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect = {
	effect: animation4,
	repeat: false,
	startDelay: 0.2,
	threshold: 0,
	tokenization: "word",
	transition: transition22,
	trigger: "onInView",
	type: "appear",
};
var transition32 = {
	damping: 100,
	delay: 0.01,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect1 = {
	effect: animation4,
	repeat: false,
	startDelay: 0.3,
	threshold: 0,
	tokenization: "word",
	transition: transition32,
	trigger: "onInView",
	type: "appear",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "XCrIpY8RT",
	Phone: "sQyJ43R8p",
	Tablet: "bDwpUZwbz",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "XCrIpY8RT",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "XCrIpY8RT",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-2tptxy",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"XCrIpY8RT"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						{...addPropertyOverrides2(
							{
								bDwpUZwbz: {
									"data-framer-name": "Tablet",
								},
								sQyJ43R8p: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-ce18et"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"fiwcNoXsV"}
						>
							<motion2.div
								className={"framer-9fd6cz"}
								data-framer-name={"heading"}
								layoutDependency={layoutDependency}
								layoutId={"MvrCZbG8J"}
							>
								<motion2.div
									className={"framer-1k8m0it"}
									data-framer-name={"text"}
									layoutDependency={layoutDependency}
									layoutId={"iLzE5g3pQ"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-z84ciu"}
										data-framer-name={
											"An Exclusive Community for lead generation experts"
										}
										effect={textEffect}
										fonts={["FS;Plus Jakarta Sans-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"zEYU0nmiA"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(22, 16, 30))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												style={{
													"--font-selector":
														"RlM7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
													"--framer-font-family":
														'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
													"--framer-font-size": "56px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "120%",
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(22, 16, 30)))",
												}}
											>
												{"Frequently Asked Questions"}
											</motion2.h2>
										</React2.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-tcbx5h"}
										data-framer-name={
											"Lead Academy is an academy & community dedicated for lead generation experts & students to share information & grow through collaborative efforts."
										}
										effect={textEffect1}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ECy19RrJ7"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(22, 16, 30))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--framer-line-height": "150%",
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(22, 16, 30)))",
												}}
											>
												{"Everything you need to know."}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-eqlb70"}
								data-framer-name={"faq's container"}
								layoutDependency={layoutDependency}
								layoutId={"DXQGs3Xho"}
							>
								<ComponentViewportProvider2
									height={304}
									width={`min(min(${componentViewport?.width || "100vw"} - 80px, 1200px), 600px)`}
									y={
										(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 722) - 200 - 551.2) / 2 +
											0 +
											0) +
										0 +
										247.2 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											sQyJ43R8p: {
												width: `min(min(${componentViewport?.width || "100vw"} - 36px, 1200px), 600px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 551.2) /
														2 +
														0 +
														0) +
													0 +
													247.2 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1kc815v-container"}
										data-framer-name={"FAQs"}
										layoutDependency={layoutDependency}
										layoutId={"myFxzfTub-container"}
										name={"FAQs"}
										nodeId={"myFxzfTub"}
										rendersWithMotion={true}
										scopeId={"pcLbbCzbS"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "myFxzfTub",
											layoutId: "myFxzfTub",
											name: "FAQs",
											style: {
												width: "100%",
											},
											variant: "zmrpr3jwr",
											width: "100%",
											...addPropertyOverrides2(
												{
													sQyJ43R8p: {
														variant: "kYaPHD6hb",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hLqW0.framer-1ttfxg9, .framer-hLqW0 .framer-1ttfxg9 { display: block; }",
	".framer-hLqW0.framer-2tptxy { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 40px 100px 40px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-hLqW0 .framer-ce18et { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 44px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-hLqW0 .framer-9fd6cz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 640px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-hLqW0 .framer-1k8m0it { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hLqW0 .framer-z84ciu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 2; }",
	".framer-hLqW0 .framer-tcbx5h { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-hLqW0 .framer-eqlb70 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; max-width: 600px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hLqW0 .framer-1kc815v-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-hLqW0.framer-v-115a22f.framer-2tptxy { width: 810px; }",
	".framer-hLqW0.framer-v-1ro9jv2.framer-2tptxy { padding: 80px 18px 80px 18px; width: 390px; }",
];
var FramerpcLbbCzbS = withCSS2(Component2, css2, "framer-hLqW0");
var stdin_default3 = FramerpcLbbCzbS;
FramerpcLbbCzbS.displayName = "Faq's section";
FramerpcLbbCzbS.defaultProps = {
	height: 722,
	width: 1200,
};
addPropertyControls2(FramerpcLbbCzbS, {
	variant: {
		options: ["XCrIpY8RT", "bDwpUZwbz", "sQyJ43R8p"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerpcLbbCzbS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Plus Jakarta Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TX2N2Q6ZO2LBO34H72H5RVJTBQFGU4GV/ZICVNTLTT4V7CCIJPWNY363N6LIP2AET/OUUAK2X2MEGEKC6ULA4CFSBY4PE5EGPV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CardsFAQFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-s-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sQyJ43R8p",
	md: "bDwpUZwbz",
	xl: "XCrIpY8RT",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders FaqSSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var faq_s_section_default = ComponentWithRoot;
export { faq_s_section_default as default };
