// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Expert market knowledge' | 'Strong communication' | 'Professionalism' // Variant
 * direction?: 'Horizontal' | 'Vertical' // Direction
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:features
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/features-rj3F.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	Image,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/RmFE3kAo5mPixQbEDATL/13DS7t64aBHBRgb5r1Dw/UMhjBSM_3.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/32x8Zt2dMTlqItGAc8if/EekVdd3cpEGQiCjXdx20/qRlZLkbik.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-ah5dt .framer-styles-preset-zo64ly:not(.rich-text-wrapper), .framer-ah5dt .framer-styles-preset-zo64ly.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'ss01' on, 'ss07' on, 'salt' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className = "framer-ah5dt";

// /:https://framerusercontent.com/modules/RmFE3kAo5mPixQbEDATL/13DS7t64aBHBRgb5r1Dw/UMhjBSM_3.js
var serializationHash = "framer-KM0iW";
var variantClassNames = {
	gZFDU6I13: "framer-v-zrk4vz",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		ASxCq3uAV: title ?? props.ASxCq3uAV ?? "Features",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ASxCq3uAV,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "gZFDU6I13",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-zrk4vz",
							className2,
							classNames,
						)}
						data-framer-name={"tag"}
						layoutDependency={layoutDependency}
						layoutId={"gZFDU6I13"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-d4bef0ce-3289-4144-af2e-3b2f9e76ab97, rgb(120, 175, 207))",
							borderBottomLeftRadius: 17,
							borderBottomRightRadius: 17,
							borderTopLeftRadius: 17,
							borderTopRightRadius: 17,
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1aqq57a"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"hfRuEqdfl"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-e816f309-d73f-4ac5-ab81-28544e225f69, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={ASxCq3uAV}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-zo64ly"}
									data-styles-preset={"qRlZLkbik"}
									style={{
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-e816f309-d73f-4ac5-ab81-28544e225f69, rgb(255, 255, 255)))",
									}}
								>
									{"Features"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KM0iW.framer-1ctlmkt, .framer-KM0iW .framer-1ctlmkt { display: block; }",
	".framer-KM0iW.framer-zrk4vz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 7px 16px 7px 16px; position: relative; width: min-content; }",
	".framer-KM0iW .framer-1aqq57a { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	...css,
];
var FramerUMhjBSM_3 = withCSS(Component, css2, "framer-KM0iW");
var stdin_default = FramerUMhjBSM_3;
FramerUMhjBSM_3.displayName = "tag";
FramerUMhjBSM_3.defaultProps = {
	height: 34,
	width: 92,
};
addPropertyControls(FramerUMhjBSM_3, {
	ASxCq3uAV: {
		defaultValue: "Features",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerUMhjBSM_3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/features-rj3F.js
var TagFonts = getFonts(stdin_default);
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText2),
);
var cycleOrder = ["L8ahxkvJ_", "bDo56SJYA", "t30eSD8X3"];
var serializationHash2 = "framer-ppjVh";
var variantClassNames2 = {
	bDo56SJYA: "framer-v-4az5f1",
	L8ahxkvJ_: "framer-v-j15l9t",
	t30eSD8X3: "framer-v-ickzie",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition12,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	Horizontal: "row",
	Vertical: "column",
};
var humanReadableVariantMap = {
	"Expert market knowledge": "L8ahxkvJ_",
	"Strong communication": "bDo56SJYA",
	Professionalism: "t30eSD8X3",
};
var getProps2 = ({ direction, height, id, width, ...props }) => {
	return {
		...props,
		cF02Wtat_:
			humanReadableEnumMap[direction] ?? direction ?? props.cF02Wtat_ ?? "row",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "L8ahxkvJ_",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		cF02Wtat_,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "L8ahxkvJ_",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapi8xbr2 = activeVariantCallback(async (...args) => {
		setVariant("L8ahxkvJ_");
	});
	const onTap1o2aw9a = activeVariantCallback(async (...args) => {
		setVariant("bDo56SJYA");
	});
	const onTap4vjenc = activeVariantCallback(async (...args) => {
		setVariant("t30eSD8X3");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["bDo56SJYA", "t30eSD8X3"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "bDo56SJYA") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "t30eSD8X3") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-j15l9t",
							className2,
							classNames,
						)}
						data-framer-name={"Expert market knowledge"}
						layoutDependency={layoutDependency}
						layoutId={"L8ahxkvJ_"}
						ref={refBinding}
						style={{
							"--12xp7b6": cF02Wtat_,
							"--1qnz49i": cF02Wtat_ === "column" ? "100%" : "1px",
							"--v2pzew": cF02Wtat_ === "row" ? "100%" : "1px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bDo56SJYA: {
									"data-framer-name": "Strong communication",
								},
								t30eSD8X3: {
									"data-framer-name": "Professionalism",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-4ayob2"}
							data-framer-name={"content"}
							layoutDependency={layoutDependency}
							layoutId={"tz2gbSr9x"}
						>
							<motion2.div
								className={"framer-1qariq6"}
								data-framer-name={"header"}
								layoutDependency={layoutDependency}
								layoutId={"yu81gOIi6"}
							>
								<ComponentViewportProvider height={34}>
									<SmartComponentScopedContainer
										className={"framer-162o5it-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"Fb306bNJm-container"}
										nodeId={"Fb306bNJm"}
										rendersWithMotion={true}
										scopeId={"aVgg57gcv"}
									>
										{_jsx2(stdin_default, {
											ASxCq3uAV: "Features",
											height: "100%",
											id: "Fb306bNJm",
											layoutId: "Fb306bNJm",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion2.div
									className={"framer-zzjcax"}
									data-framer-name={"text"}
									layoutDependency={layoutDependency}
									layoutId={"lrQKeL3Cn"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-148qtyr"}
										fonts={["FR;InterDisplay-Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"RVJ4rVh0z"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												style={{
													"--font-selector": "RlI7SW50ZXJEaXNwbGF5LU1lZGl1bQ==",
													"--framer-font-family":
														'"Inter Display", "Inter Display Placeholder", sans-serif',
													"--framer-font-size": "42px",
													"--framer-font-weight": "500",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0)))",
												}}
											>
												{"Discover our features"}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-hlalyu"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"cfUxM9C1j"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--framer-font-size": "18px",
													"--framer-line-height": "1.4em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92)))",
												}}
											>
												{"Features built to simplify your journey."}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-sop4we"}
								data-framer-name={"container"}
								layoutDependency={layoutDependency}
								layoutId={"CglIXOVye"}
							>
								<motion2.div
									className={"framer-zt1c8i"}
									data-border={true}
									data-framer-name={"1st"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"ial3QOcti"}
									onTap={onTapi8xbr2}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-b0e6538b-50e3-4172-ac6e-a172ae15d830, rgb(228, 231, 236))",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									}}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1t32ueq"}
										fonts={["FR;InterDisplay-Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"iI7FGrjQE"}
										style={{
											"--extracted-1eung3n":
												"var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												style={{
													"--font-selector": "RlI7SW50ZXJEaXNwbGF5LU1lZGl1bQ==",
													"--framer-font-family":
														'"Inter Display", "Inter Display Placeholder", sans-serif',
													"--framer-font-size": "22px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0)))",
												}}
											>
												{"Expert market knowledge"}
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									{isDisplayed() && (
										<RichTextWithFXWithOptimizedAppearEffect
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation}
											className={"framer-yrb0tp"}
											data-framer-appear-id={"yrb0tp"}
											fonts={["Inter"]}
											initial={animation1}
											layoutDependency={layoutDependency}
											layoutId={"UbczqdMSJ"}
											optimized={true}
											style={{
												"--extracted-r6o4lv":
													"var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--framer-line-height": "1.6em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92)))",
													}}
												>
													{
														"A real estate company with strong market expertise can offer valuable insights."
													}
												</motion2.p>
											</React2.Fragment>
										</RichTextWithFXWithOptimizedAppearEffect>
									)}
								</motion2.div>
								<motion2.div
									className={"framer-1tkb6o"}
									data-border={true}
									data-framer-name={"2nd"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"RG7LjokBn"}
									onTap={onTap1o2aw9a}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-b0e6538b-50e3-4172-ac6e-a172ae15d830, rgb(228, 231, 236))",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									}}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-f9qtbt"}
										fonts={["FR;InterDisplay-Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"xQqNlm8m4"}
										style={{
											"--extracted-1eung3n":
												"var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												style={{
													"--font-selector": "RlI7SW50ZXJEaXNwbGF5LU1lZGl1bQ==",
													"--framer-font-family":
														'"Inter Display", "Inter Display Placeholder", sans-serif',
													"--framer-font-size": "22px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0)))",
												}}
											>
												{"Strong communication"}
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									{isDisplayed1() && (
										<RichTextWithFXWithOptimizedAppearEffect
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation}
											className={"framer-1fpcyho"}
											data-framer-appear-id={"1fpcyho"}
											fonts={["Inter"]}
											initial={animation1}
											layoutDependency={layoutDependency}
											layoutId={"NmvmV9HuR"}
											optimized={true}
											style={{
												"--extracted-r6o4lv":
													"var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--framer-line-height": "1.6em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92)))",
													}}
												>
													{
														"Keeping clients updated at every stage, from new listings to final offers, ensures a smooth process."
													}
												</motion2.p>
											</React2.Fragment>
										</RichTextWithFXWithOptimizedAppearEffect>
									)}
								</motion2.div>
								<motion2.div
									className={"framer-1x3fm5f"}
									data-border={true}
									data-framer-name={"3rd"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"oZIr1clPq"}
									onTap={onTap4vjenc}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-b0e6538b-50e3-4172-ac6e-a172ae15d830, rgb(228, 231, 236))",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									}}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-5i1zui"}
										fonts={["FR;InterDisplay-Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"K64gEJOWs"}
										style={{
											"--extracted-1eung3n":
												"var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												style={{
													"--font-selector": "RlI7SW50ZXJEaXNwbGF5LU1lZGl1bQ==",
													"--framer-font-family":
														'"Inter Display", "Inter Display Placeholder", sans-serif',
													"--framer-font-size": "22px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-e470dd81-4f9c-435c-bc58-8c2fe6e53df2, rgb(0, 0, 0)))",
												}}
											>
												{"Professionalism"}
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									{isDisplayed2() && (
										<RichTextWithFXWithOptimizedAppearEffect
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation}
											className={"framer-124in56"}
											data-framer-appear-id={"124in56"}
											fonts={["Inter"]}
											initial={animation1}
											layoutDependency={layoutDependency}
											layoutId={"to22tbhR6"}
											optimized={true}
											style={{
												"--extracted-r6o4lv":
													"var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--framer-line-height": "1.6em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-083a6ecc-3ad4-4fb3-a1c5-df9ad6142cea, rgb(92, 92, 92)))",
													}}
												>
													{
														"A professional company is committed to ethical practices, offering dependable guidance and maintaining a high level of service."
													}
												</motion2.p>
											</React2.Fragment>
										</RichTextWithFXWithOptimizedAppearEffect>
									)}
								</motion2.div>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-1nn8tjy"}
							data-framer-name={"images"}
							layoutDependency={layoutDependency}
							layoutId={"xOUm3I0BY"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 1200,
									pixelWidth: 904,
									sizes:
										cF02Wtat_ === "row"
											? `max((${componentViewport?.width || "100vw"} - 24px) / 2, 1px)`
											: componentViewport?.width || "100vw",
									src: "https://framerusercontent.com/images/FnGLm2yRNviYdXrQyrqRuUBnz0.png",
									srcSet:
										"https://framerusercontent.com/images/FnGLm2yRNviYdXrQyrqRuUBnz0.png?scale-down-to=1024 771w,https://framerusercontent.com/images/FnGLm2yRNviYdXrQyrqRuUBnz0.png 904w",
								}}
								className={"framer-1mx7a47"}
								data-framer-name={"image"}
								layoutDependency={layoutDependency}
								layoutId={"gE7tij7nT"}
								style={{
									borderBottomLeftRadius: 18,
									borderBottomRightRadius: 18,
									borderTopLeftRadius: 18,
									borderTopRightRadius: 18,
									opacity: 1,
								}}
								variants={{
									bDo56SJYA: {
										opacity: 0,
									},
									t30eSD8X3: {
										opacity: 0,
									},
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 800,
									pixelWidth: 1200,
									sizes:
										cF02Wtat_ === "row"
											? `max((${componentViewport?.width || "100vw"} - 24px) / 2, 1px)`
											: componentViewport?.width || "100vw",
									src: "https://framerusercontent.com/images/PjHJMX19p4rUgEbsFA6rEDDges.png",
									srcSet:
										"https://framerusercontent.com/images/PjHJMX19p4rUgEbsFA6rEDDges.png?scale-down-to=512 512w,https://framerusercontent.com/images/PjHJMX19p4rUgEbsFA6rEDDges.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/PjHJMX19p4rUgEbsFA6rEDDges.png 1200w",
								}}
								className={"framer-x5frqq"}
								data-framer-name={"image"}
								layoutDependency={layoutDependency}
								layoutId={"ikryzLJm_"}
								style={{
									borderBottomLeftRadius: 18,
									borderBottomRightRadius: 18,
									borderTopLeftRadius: 18,
									borderTopRightRadius: 18,
									opacity: 0,
								}}
								variants={{
									bDo56SJYA: {
										opacity: 1,
									},
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 923,
									pixelWidth: 1200,
									sizes:
										cF02Wtat_ === "row"
											? `max((${componentViewport?.width || "100vw"} - 24px) / 2, 1px)`
											: componentViewport?.width || "100vw",
									src: "https://framerusercontent.com/images/OKoiSJ7boY71o8nLuIvbtaihs4.png",
									srcSet:
										"https://framerusercontent.com/images/OKoiSJ7boY71o8nLuIvbtaihs4.png?scale-down-to=512 512w,https://framerusercontent.com/images/OKoiSJ7boY71o8nLuIvbtaihs4.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/OKoiSJ7boY71o8nLuIvbtaihs4.png 1200w",
								}}
								className={"framer-12a5n8s"}
								data-framer-name={"image"}
								layoutDependency={layoutDependency}
								layoutId={"Rqa1bPkrn"}
								style={{
									borderBottomLeftRadius: 18,
									borderBottomRightRadius: 18,
									borderTopLeftRadius: 18,
									borderTopRightRadius: 18,
									opacity: 0,
								}}
								variants={{
									t30eSD8X3: {
										opacity: 1,
									},
								}}
							/>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ppjVh.framer-1hkv9wd, .framer-ppjVh .framer-1hkv9wd { display: block; }",
	".framer-ppjVh.framer-j15l9t { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: var(--12xp7b6); flex-wrap: nowrap; gap: 24px 24px; height: 600px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1120px; }",
	".framer-ppjVh .framer-4ayob2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: var(--v2pzew); justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: var(--1qnz49i); }",
	".framer-ppjVh .framer-1qariq6, .framer-ppjVh .framer-zzjcax { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ppjVh .framer-162o5it-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-ppjVh .framer-148qtyr, .framer-ppjVh .framer-1t32ueq, .framer-ppjVh .framer-yrb0tp, .framer-ppjVh .framer-f9qtbt, .framer-ppjVh .framer-1fpcyho, .framer-ppjVh .framer-5i1zui, .framer-ppjVh .framer-124in56 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ppjVh .framer-hlalyu { flex: none; height: auto; max-width: 330px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ppjVh .framer-sop4we { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; user-select: none; width: 100%; }",
	".framer-ppjVh .framer-zt1c8i { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 24px 0px; position: relative; width: 100%; }",
	".framer-ppjVh .framer-1tkb6o, .framer-ppjVh .framer-1x3fm5f { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 24px 0px; position: relative; width: 100%; }",
	".framer-ppjVh .framer-1nn8tjy { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--v2pzew); justify-content: center; overflow: visible; padding: 0px; position: relative; width: var(--1qnz49i); }",
	".framer-ppjVh .framer-1mx7a47 { -webkit-user-select: none; bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; user-select: none; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-ppjVh .framer-x5frqq, .framer-ppjVh .framer-12a5n8s { -webkit-user-select: none; bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; user-select: none; will-change: var(--framer-will-change-override, transform); }",
	".framer-ppjVh.framer-v-4az5f1 .framer-1mx7a47, .framer-ppjVh.framer-v-ickzie .framer-1mx7a47 { z-index: unset; }",
	'.framer-ppjVh[data-border="true"]::after, .framer-ppjVh [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameraVgg57gcv = withCSS2(Component2, css3, "framer-ppjVh");
var stdin_default2 = FrameraVgg57gcv;
FrameraVgg57gcv.displayName = "features";
FrameraVgg57gcv.defaultProps = {
	height: 600,
	width: 1120,
};
addPropertyControls2(FrameraVgg57gcv, {
	variant: {
		options: ["L8ahxkvJ_", "bDo56SJYA", "t30eSD8X3"],
		optionTitles: [
			"Expert market knowledge",
			"Strong communication",
			"Professionalism",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	cF02Wtat_: {
		defaultValue: "row",
		displaySegmentedControl: true,
		optionIcons: ["direction-horizontal", "direction-vertical"],
		options: ["row", "column"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Direction",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FrameraVgg57gcv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/ePuN3mCjzajIHnyCdvKBFiZkyY0.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/V3j1L0o5vPFKe26Sw4HcpXCfHo.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/F3kdpd2N0cToWV5huaZjjgM.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/0iDmxkizU9goZoclqIqsV5rvETU.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/r0mv3NegmA0akcQsNFotG32Las.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/8yoV9pUxquX7VD7ZXlNYKQmkmk.woff2",
					weight: "500",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/Ii21jnSJkulBKsHHXKlapi7fv9w.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders FeaturesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var features_default = ComponentWithRoot;
export { features_default as default };
