// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Small' // Variant
 * title?: string // Title
 * description?: string // Description
 * time?: string // Time
 * appImage?: {src: string, srcSet?: string, alt?: string} // App Image
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { className, css, fonts } from "./chunks/chunk-LYSX2AAY.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KHUWPRRZ.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:ios-notification
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/iosNotification-ngnZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["LoOxGxhOH", "GYb1oGn8X"];
var serializationHash = "framer-G2yUt";
var variantClassNames = {
	GYb1oGn8X: "framer-v-2jyd2v",
	LoOxGxhOH: "framer-v-1atmt2y",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "LoOxGxhOH",
	Small: "GYb1oGn8X",
};
var getProps = ({
	appImage,
	description,
	height,
	id,
	time,
	title,
	width,
	...props
}) => {
	return {
		...props,
		aIAnBgvn9: time ?? props.aIAnBgvn9 ?? "9:41 AM",
		cLvgks9Mx: title ?? props.cLvgks9Mx ?? "Title",
		jQtXhlgn6: description ?? props.jQtXhlgn6 ?? "Description",
		v2WEVmkpB: appImage ??
			props.v2WEVmkpB ?? {
				pixelHeight: 180,
				pixelWidth: 180,
				src: "https://framerusercontent.com/images/BJRMPP2TSh030DhJrCY22gMyBy8.png",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LoOxGxhOH",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		cLvgks9Mx,
		jQtXhlgn6,
		aIAnBgvn9,
		v2WEVmkpB,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LoOxGxhOH",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1atmt2y",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"LoOxGxhOH"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-01bbde25-05c9-4f10-9741-7a896669af2f, rgb(239, 241, 243))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(4px)",
							backgroundColor: "rgba(252, 252, 252, 0.53)",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							WebkitBackdropFilter: "blur(4px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								GYb1oGn8X: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(14 + ((componentViewport?.height || 82) - 26 - 53) / 2),
								),
								sizes: "53px",
								...toResponsiveImage(v2WEVmkpB),
							}}
							className={"framer-13k0w1"}
							data-framer-name={"App Icon"}
							layoutDependency={layoutDependency}
							layoutId={"hV6ROgsGM"}
							style={{
								borderBottomLeftRadius: 8.5,
								borderBottomRightRadius: 8.5,
								borderTopLeftRadius: 8.5,
								borderTopRightRadius: 8.5,
							}}
						/>
						<motion.div
							className={"framer-mxxjjy"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"FaW5IRYhA"}
						>
							<motion.div
								className={"framer-18pa1f1"}
								data-framer-name={"Title + Time"}
								layoutDependency={layoutDependency}
								layoutId={"ul4XGgzkx"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1t9rmsk"}
									data-framer-name={"Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ftt5oGvDF"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={cLvgks9Mx}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-erxpvx"}
											data-styles-preset={"nzdW7Y_Eq"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0)))",
											}}
										>
											{"Title"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-r0dw0q"}
									data-framer-name={"Time"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"YzeDYRyzi"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-bdf3e9f8-3d6a-4deb-aca6-dd00e261811d, rgb(125, 97, 97))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={aIAnBgvn9}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-bdf3e9f8-3d6a-4deb-aca6-dd00e261811d, rgb(125, 97, 97)))",
											}}
										>
											{"9:41 AM"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-btz4ph"}
								data-framer-name={"Description"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"lFnDc0WY9"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-bdf3e9f8-3d6a-4deb-aca6-dd00e261811d, rgb(125, 97, 97))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={jQtXhlgn6}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1hj8z0a"}
										data-styles-preset={"UByHkDadJ"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-bdf3e9f8-3d6a-4deb-aca6-dd00e261811d, rgb(125, 97, 97)))",
										}}
									>
										{"Description"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-G2yUt.framer-6bf6m3, .framer-G2yUt .framer-6bf6m3 { display: block; }",
	".framer-G2yUt.framer-1atmt2y { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 82px; justify-content: center; overflow: hidden; padding: 14px 14px 12px 14px; position: relative; width: 432px; will-change: var(--framer-will-change-override, transform); }",
	".framer-G2yUt .framer-13k0w1 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 53px); position: relative; width: 53px; }",
	".framer-G2yUt .framer-mxxjjy { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-G2yUt .framer-18pa1f1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-G2yUt .framer-1t9rmsk { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-G2yUt .framer-r0dw0q { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-G2yUt .framer-btz4ph { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-G2yUt.framer-1atmt2y, .framer-G2yUt .framer-mxxjjy, .framer-G2yUt .framer-18pa1f1 { gap: 0px; } .framer-G2yUt.framer-1atmt2y > *, .framer-G2yUt .framer-18pa1f1 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-G2yUt.framer-1atmt2y > :first-child, .framer-G2yUt .framer-18pa1f1 > :first-child { margin-left: 0px; } .framer-G2yUt.framer-1atmt2y > :last-child, .framer-G2yUt .framer-18pa1f1 > :last-child { margin-right: 0px; } .framer-G2yUt .framer-mxxjjy > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-G2yUt .framer-mxxjjy > :first-child { margin-top: 0px; } .framer-G2yUt .framer-mxxjjy > :last-child { margin-bottom: 0px; } }",
	".framer-G2yUt.framer-v-2jyd2v.framer-1atmt2y { width: 376px; }",
	...css,
	...css2,
	'.framer-G2yUt[data-border="true"]::after, .framer-G2yUt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerI9B4rfYlA = withCSS(Component, css3, "framer-G2yUt");
var stdin_default = FramerI9B4rfYlA;
FramerI9B4rfYlA.displayName = "iosNotification";
FramerI9B4rfYlA.defaultProps = {
	height: 82,
	width: 432,
};
addPropertyControls(FramerI9B4rfYlA, {
	variant: {
		options: ["LoOxGxhOH", "GYb1oGn8X"],
		optionTitles: ["Variant 1", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	cLvgks9Mx: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	jQtXhlgn6: {
		defaultValue: "Description",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	aIAnBgvn9: {
		defaultValue: "9:41 AM",
		displayTextArea: false,
		title: "Time",
		type: ControlType.String,
	},
	v2WEVmkpB: {
		__defaultAssetReference:
			"data:framer/asset-reference,BJRMPP2TSh030DhJrCY22gMyBy8.png?originalFilename=No+App+Icon.png&preferredSize=auto",
		title: "App Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerI9B4rfYlA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:ios-notification
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LoOxGxhOH",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders IosNotificationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var ios_notification_default = ComponentWithRoot;
export { ios_notification_default as default };
