// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Variant' | 'Variant' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
	stdin_default,
} from "./chunks/chunk-XLXKYAVK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6FB2SUDJ.js";
import { className, css, fonts } from "./chunks/chunk-PU7BSL5Q.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:main
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Main-E0Tx.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition as getLoadingLazyAtYPosition2,
	Image as Image2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX as withFX2,
	withOptimizedAppearEffect as withOptimizedAppearEffect2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/3AN7JQ8lFHVOtOLEUowo/ZJC3ZNfnNCV6Ab9wgcMB/pcuK4Mnm2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonsButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var ImageWithFX = withFX(Image);
var serializationHash = "framer-xqNAT";
var variantClassNames = {
	sdd07EdxS: "framer-v-1xxwjwe",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition2 = {
	delay: 0,
	duration: 1.8,
	ease: [0.67, 0.33, 0.23, 1.02],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.7,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 1.6,
	ease: [0.67, 0.33, 0.23, 1.02],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation3 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1.4,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition4 = {
	delay: 0.05,
	duration: 0.45,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var textEffect = {
	effect: animation3,
	repeat: false,
	startDelay: 0,
	tokenization: "character",
	transition: transition4,
	trigger: "onMount",
	type: "appear",
};
var animation4 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition5 = {
	bounce: 0,
	delay: 0.01,
	duration: 0.2,
	type: "spring",
};
var textEffect1 = {
	effect: animation4,
	startDelay: 1.5,
	tokenization: "character",
	transition: transition5,
	trigger: "onMount",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "sdd07EdxS",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<ImageWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__adjustPosition={false}
						__framer__offset={0}
						__framer__parallaxTransformEnabled={true}
						__framer__speed={80}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 2735,
							intrinsicWidth: 2191,
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 4403,
							pixelWidth: 1920,
							positionX: "center",
							positionY: "top",
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=4096",
							srcSet:
								"https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=2048 893w,https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/7EwxWXew8omDoKKlsGNelUf1TxY.png 1920w",
						}}
						className={cx(
							scopingClassNames,
							"framer-1xxwjwe",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"sdd07EdxS"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 958,
								),
								pixelHeight: 661,
								pixelWidth: 1080,
								sizes: "263px",
								src: "https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png",
								srcSet:
									"https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/w5BfUmpOIjbAbl2b1JWQM1bAswQ.png 1080w",
							}}
							className={"framer-1huniq5"}
							layoutDependency={layoutDependency}
							layoutId={"dtZpANgkj"}
						/>
						<ComponentViewportProvider
							height={52}
							y={(componentViewport?.y || 0) + 543}
						>
							<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={100}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-18dm7lu-container"}
								data-framer-appear-id={"18dm7lu"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"IYdljxCcJ-container"}
								nodeId={"IYdljxCcJ"}
								optimized={true}
								rendersWithMotion={true}
								scopeId={"pcuK4Mnm2"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									cRoeZpcrs: "Join The Waitlist - Get Early Access",
									FsefAOOPs:
										"var(--token-d49ce14e-f5dc-463a-9b8d-4f0e772df7f1, rgb(255, 255, 255))",
									height: "100%",
									id: "IYdljxCcJ",
									layoutId: "IYdljxCcJ",
									SM93ZbT4W: true,
									variant: "ElkbJxbcB",
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
						</ComponentViewportProvider>
						<RichTextWithFXWithOptimizedAppearEffect
							__framer__adjustPosition={false}
							__framer__offset={0}
							__framer__parallaxTransformEnabled={true}
							__framer__speed={100}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation2}
							className={"framer-1ilmqqm"}
							data-framer-appear-id={"1ilmqqm"}
							effect={textEffect}
							fonts={["Inter"]}
							initial={animation1}
							layoutDependency={layoutDependency}
							layoutId={"yszxu4bpb"}
							optimized={true}
							style={{
								"--extracted-gdpscs":
									"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									className={"framer-styles-preset-1jo3glk"}
									data-styles-preset={"enXnUuyN7"}
									style={{
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-gdpscs, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11)))",
									}}
								>
									{"Control your X feed."}
									<motion.br />
									{"No more noise. Just signal."}
								</motion.h1>
							</React.Fragment>
						</RichTextWithFXWithOptimizedAppearEffect>
						<RichTextWithFXWithOptimizedAppearEffect
							__framer__adjustPosition={false}
							__framer__offset={0}
							__framer__parallaxTransformEnabled={true}
							__framer__speed={100}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation2}
							className={"framer-frtxnb"}
							data-framer-appear-id={"frtxnb"}
							effect={textEffect1}
							fonts={["Inter"]}
							initial={animation1}
							layoutDependency={layoutDependency}
							layoutId={"MfY8AJTFJ"}
							optimized={true}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h3
									className={"framer-styles-preset-1tsd54f"}
									data-styles-preset={"DhsVO3ura"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{
										"Follow anyone. See only what matters - from a list that you control."
									}
								</motion.h3>
							</React.Fragment>
						</RichTextWithFXWithOptimizedAppearEffect>
					</ImageWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xqNAT.framer-176dcq2, .framer-xqNAT .framer-176dcq2 { display: block; }",
	".framer-xqNAT.framer-1xxwjwe { height: 3092px; overflow: visible; position: relative; width: 1440px; }",
	".framer-xqNAT .framer-1huniq5 { flex: none; height: 115px; left: calc(50.00000000000002% - 263px / 2); position: absolute; top: 958px; width: 263px; }",
	".framer-xqNAT .framer-18dm7lu-container { flex: none; height: auto; left: 50%; position: absolute; top: 543px; width: auto; z-index: 3; }",
	".framer-xqNAT .framer-1ilmqqm { flex: none; height: auto; left: 50%; position: absolute; top: 274px; white-space: pre; width: auto; z-index: 1; }",
	".framer-xqNAT .framer-frtxnb { flex: none; height: auto; left: 50%; position: absolute; top: 451px; white-space: pre; width: auto; z-index: 1; }",
	...css3,
	...css,
];
var FramerpcuK4Mnm2 = withCSS(Component, css4, "framer-xqNAT");
var stdin_default2 = FramerpcuK4Mnm2;
FramerpcuK4Mnm2.displayName = "background";
FramerpcuK4Mnm2.defaultProps = {
	height: 3092,
	width: 1440,
};
addFonts(
	FramerpcuK4Mnm2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonsButtonFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Main-E0Tx.js
var BackgroundFonts = getFonts2(stdin_default2);
var ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect2(
	withFX2(Image2),
);
var ImageWithFX2 = withFX2(Image2);
var RichTextWithFXWithOptimizedAppearEffect2 = withOptimizedAppearEffect2(
	withFX2(RichText2),
);
var cycleOrder = [
	"S48s0AycK",
	"oxU6qnjj1",
	"TKuC5YVdc",
	"hEtixOw54",
	"Cm2oxkrAC",
];
var serializationHash2 = "framer-x6ZFx";
var variantClassNames2 = {
	Cm2oxkrAC: "framer-v-qtj6h4",
	hEtixOw54: "framer-v-1cu09ka",
	oxU6qnjj1: "framer-v-d7wzbt",
	S48s0AycK: "framer-v-jx0221",
	TKuC5YVdc: "framer-v-19556c",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition22 = {
	delay: 0.6,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition22,
	x: 0,
	y: 0,
};
var animation12 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -150,
};
var transformTemplate12 = (_, t) => `translateX(-50%) ${t}`;
var transition32 = {
	delay: 0,
	duration: 1.6,
	ease: [0.67, 0.33, 0.23, 1.02],
	type: "tween",
};
var animation22 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition32,
	x: 0,
	y: 0,
};
var animation32 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.7,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var animation42 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1.4,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition42 = {
	delay: 0.05,
	duration: 0.45,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var textEffect2 = {
	effect: animation42,
	repeat: false,
	startDelay: 0,
	tokenization: "character",
	transition: transition42,
	trigger: "onMount",
	type: "appear",
};
var animation52 = {
	filter: "blur(6px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition52 = {
	bounce: 0,
	delay: 0.01,
	duration: 0.2,
	type: "spring",
};
var textEffect12 = {
	effect: animation52,
	startDelay: 1.5,
	tokenization: "character",
	transition: transition52,
	trigger: "onMount",
	type: "appear",
};
var animation6 = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition6 = {
	bounce: 0,
	delay: 0.05,
	duration: 0.4,
	type: "spring",
};
var textEffect22 = {
	effect: animation6,
	startDelay: 1.5,
	tokenization: "character",
	transition: transition6,
	trigger: "onMount",
	type: "appear",
};
var transition7 = {
	delay: 0.3,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation7 = {
	opacity: 0.92,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var animation8 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.6,
	skewX: 0,
	skewY: 0,
	x: 150,
	y: 0,
};
var animation9 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var animation10 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -150,
	y: 0,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Desktop: "S48s0AycK",
	Phone: "Cm2oxkrAC",
	Tablet: "hEtixOw54",
	Variant: "TKuC5YVdc",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "S48s0AycK",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "S48s0AycK",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "Cm2oxkrAC") return false;
		return true;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-jx0221",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"S48s0AycK"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Cm2oxkrAC: {
									"data-framer-name": "Phone",
								},
								hEtixOw54: {
									"data-framer-name": "Tablet",
								},
								oxU6qnjj1: {
									"data-framer-name": void 0,
								},
								TKuC5YVdc: {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={
								Math.max(0, ((componentViewport?.height || 3092) - 0 - 0) / 1) *
								1
							}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
							{...addPropertyOverrides(
								{
									Cm2oxkrAC: {
										height: 1126.6467,
									},
									hEtixOw54: {
										height:
											Math.max(
												0,
												((componentViewport?.height || 3134) - 0 - 0) / 1,
											) * 1,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-1fxom9r-container"}
								layoutDependency={layoutDependency}
								layoutId={"ukPDUdX1l-container"}
								nodeId={"ukPDUdX1l"}
								rendersWithMotion={true}
								scopeId={"zeRIJ9WaQ"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "ukPDUdX1l",
									layoutId: "ukPDUdX1l",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						{isDisplayed() && (
							<ImageWithFXWithOptimizedAppearEffect
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={70}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation5}
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 1367.5,
									intrinsicWidth: 1095.5,
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) + -619,
									),
									pixelHeight: 1048,
									pixelWidth: 2987,
									sizes: componentViewport?.width || "100vw",
									src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
								}}
								className={"framer-yvj75c"}
								data-framer-appear-id={"yvj75c"}
								data-framer-name={"Foreground"}
								initial={animation12}
								layoutDependency={layoutDependency}
								layoutId={"Z9wwgKSku"}
								optimized={true}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fill",
												intrinsicHeight: 1367.5,
												intrinsicWidth: 1095.5,
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + -1360,
												),
												pixelHeight: 1048,
												pixelWidth: 2987,
												sizes: componentViewport?.width || "100vw",
												src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed() && (
							<ImageWithFX2
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={60}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={0.47}
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 1367.5,
									intrinsicWidth: 1095.5,
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) + 158,
									),
									pixelHeight: 1048,
									pixelWidth: 2987,
									positionX: "center",
									positionY: "center",
									sizes: `calc(${componentViewport?.width || "100vw"} * 0.234)`,
									src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
								}}
								className={"framer-1jmvmzo"}
								data-framer-name={"Mountain"}
								layoutDependency={layoutDependency}
								layoutId={"f3YQcPLug"}
								style={{
									opacity: 0.47,
								}}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 1367.5,
												intrinsicWidth: 1095.5,
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + 89,
												),
												pixelHeight: 1048,
												pixelWidth: 2987,
												positionX: "center",
												positionY: "center",
												sizes: "540px",
												src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed() && (
							<RichTextWithFXWithOptimizedAppearEffect2
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={100}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation22}
								className={"framer-b4yfvz"}
								data-framer-appear-id={"b4yfvz"}
								effect={textEffect2}
								fonts={["Inter"]}
								initial={animation32}
								layoutDependency={layoutDependency}
								layoutId={"RU4tpsyGN"}
								optimized={true}
								style={{
									"--extracted-gdpscs":
										"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate12}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.h1
										className={"framer-styles-preset-1jo3glk"}
										data-styles-preset={"enXnUuyN7"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11)))",
										}}
									>
										{"Control your X feed."}
										<motion2.br />
										{"No more noise. Just signal."}
									</motion2.h1>
								</React2.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect2>
						)}
						{isDisplayed() && (
							<RichTextWithFXWithOptimizedAppearEffect2
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={100}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation22}
								className={"framer-163bi49"}
								data-framer-appear-id={"163bi49"}
								effect={textEffect12}
								fonts={["Inter"]}
								initial={animation32}
								layoutDependency={layoutDependency}
								layoutId={"zlx6LhB59"}
								optimized={true}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate12}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1hj8z0a"}
														data-styles-preset={"UByHkDadJ"}
														style={{
															"--framer-text-alignment": "center",
														}}
													>
														{
															"Follow anyone. See only what matters - from a list that you control."
														}
													</motion2.p>
												</React2.Fragment>
											),
										},
										oxU6qnjj1: {
											effect: textEffect22,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.h3
										className={"framer-styles-preset-1tsd54f"}
										data-styles-preset={"DhsVO3ura"}
										style={{
											"--framer-text-alignment": "center",
										}}
									>
										{
											"Follow anyone. See only what matters - from a list that you control."
										}
									</motion2.h3>
								</React2.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect2>
						)}
						{isDisplayed() && (
							<ImageWithFX2
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={60}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={0.47}
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 1367.5,
									intrinsicWidth: 1095.5,
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) + -42,
									),
									pixelHeight: 1048,
									pixelWidth: 2987,
									positionX: "center",
									positionY: "center",
									sizes: `calc(${componentViewport?.width || "100vw"} / 3.609)`,
									src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
								}}
								className={"framer-cc8q1p"}
								data-framer-name={"Mountain"}
								layoutDependency={layoutDependency}
								layoutId={"Iu5PP5Npd"}
								style={{
									opacity: 0.47,
								}}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 1367.5,
												intrinsicWidth: 1095.5,
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + 89,
												),
												pixelHeight: 1048,
												pixelWidth: 2987,
												positionX: "center",
												positionY: "center",
												sizes: "540px",
												src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed() && (
							<ImageWithFXWithOptimizedAppearEffect
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={20}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={0.92}
								animate={animation7}
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 1367.5,
									intrinsicWidth: 1095.5,
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) + 377,
									),
									pixelHeight: 1048,
									pixelWidth: 2987,
									positionX: "center",
									positionY: "center",
									sizes: `calc(${componentViewport?.width || "100vw"} / 1.989)`,
									src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
								}}
								className={"framer-1p5w3py"}
								data-framer-appear-id={"1p5w3py"}
								data-framer-name={"Mountain"}
								initial={animation8}
								layoutDependency={layoutDependency}
								layoutId={"cxbm0WEr3"}
								optimized={true}
								style={{
									opacity: 0.92,
								}}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 1367.5,
												intrinsicWidth: 1095.5,
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + -192,
												),
												pixelHeight: 1048,
												pixelWidth: 2987,
												positionX: "center",
												positionY: "center",
												sizes: "810px",
												src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed() && (
							<ImageWithFXWithOptimizedAppearEffect
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={20}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation9}
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 1367.5,
									intrinsicWidth: 1095.5,
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) + 461,
									),
									pixelHeight: 1048,
									pixelWidth: 2987,
									positionX: "center",
									positionY: "center",
									sizes: `calc(${componentViewport?.width || "100vw"} * 0.3382)`,
									src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
								}}
								className={"framer-f3edt2"}
								data-framer-appear-id={"f3edt2"}
								data-framer-name={"Mountain"}
								initial={animation10}
								layoutDependency={layoutDependency}
								layoutId={"cL6Z7ZDj0"}
								optimized={true}
								{...addPropertyOverrides(
									{
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fit",
												intrinsicHeight: 1367.5,
												intrinsicWidth: 1095.5,
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + 318,
												),
												pixelHeight: 1048,
												pixelWidth: 2987,
												positionX: "center",
												positionY: "center",
												sizes: "810px",
												src: "https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Wc2B2ortugG9xQ0EwoP1gQO5yc.png 2987w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						<ImageWithFX2
							__framer__adjustPosition={false}
							__framer__offset={0}
							__framer__parallaxTransformEnabled={true}
							__framer__speed={80}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 1367.5,
								intrinsicWidth: 1095.5,
								loading: getLoadingLazyAtYPosition2(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 3092) * 0.5216688227684348 -
											1613),
								),
								pixelHeight: 4403,
								pixelWidth: 1920,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048",
								srcSet:
									"https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048 893w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png 1920w",
							}}
							className={"framer-7bm3kt"}
							data-framer-name={"GG"}
							layoutDependency={layoutDependency}
							layoutId={"d__iu8iHp"}
							{...addPropertyOverrides(
								{
									Cm2oxkrAC: {
										background: void 0,
									},
									hEtixOw54: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 1367.5,
											intrinsicWidth: 1095.5,
											loading: getLoadingLazyAtYPosition2(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 4403,
											pixelWidth: 1920,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048",
											srcSet:
												"https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048 893w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png 1920w",
										},
									},
									oxU6qnjj1: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 1367.5,
											intrinsicWidth: 1095.5,
											loading: getLoadingLazyAtYPosition2(
												(componentViewport?.y || 0) +
													((componentViewport?.height || 3092) *
														0.5216688227684348 -
														((componentViewport?.height || 3092) * 1.0433) / 2),
											),
											pixelHeight: 4403,
											pixelWidth: 1920,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048",
											srcSet:
												"https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048 893w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png 1920w",
										},
									},
									TKuC5YVdc: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 1367.5,
											intrinsicWidth: 1095.5,
											loading: getLoadingLazyAtYPosition2(
												(componentViewport?.y || 0) +
													((componentViewport?.height || 3092) *
														0.5216688227684348 -
														((componentViewport?.height || 3092) * 1.0433) / 2),
											),
											pixelHeight: 4403,
											pixelWidth: 1920,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048",
											srcSet:
												"https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=2048 893w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png?scale-down-to=4096 1786w,https://framerusercontent.com/images/D9i9PZwYBFi3ANCRG67LGJ7eSsc.png 1920w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image2
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition2(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 3092) *
												0.5216688227684348 -
												1613) +
											1055,
									),
									pixelHeight: 1080,
									pixelWidth: 1080,
									sizes: "263px",
									src: "https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png",
									srcSet:
										"https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=512 512w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png 1080w",
								}}
								className={"framer-1kpk8dp"}
								layoutDependency={layoutDependency}
								layoutId={"m1gPH205M"}
								style={{
									opacity: 0.3,
								}}
								{...addPropertyOverrides(
									{
										Cm2oxkrAC: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 3340) -
														(0 + (componentViewport?.height || 3340) * 1) +
														327,
												),
												pixelHeight: 1080,
												pixelWidth: 1080,
												sizes: "179px",
												src: "https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png",
												srcSet:
													"https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=512 512w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png 1080w",
											},
										},
										hEtixOw54: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) + 0 + 1033,
												),
												pixelHeight: 1080,
												pixelWidth: 1080,
												sizes: "263px",
												src: "https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png",
												srcSet:
													"https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=512 512w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png 1080w",
											},
										},
										oxU6qnjj1: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) +
														((componentViewport?.height || 3092) *
															0.5216688227684348 -
															((componentViewport?.height || 3092) * 1.0433) /
																2) +
														935,
												),
												pixelHeight: 1080,
												pixelWidth: 1080,
												sizes: "263px",
												src: "https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png",
												srcSet:
													"https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=512 512w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png 1080w",
											},
										},
										TKuC5YVdc: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition2(
													(componentViewport?.y || 0) +
														((componentViewport?.height || 3092) *
															0.5216688227684348 -
															((componentViewport?.height || 3092) * 1.0433) /
																2) +
														1023,
												),
												pixelHeight: 1080,
												pixelWidth: 1080,
												sizes: "263px",
												src: "https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png",
												srcSet:
													"https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=512 512w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/1X69nqEWRZhIEEGK3vvUJ1siDE.png 1080w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</ImageWithFX2>
						{isDisplayed() && (
							<RichTextWithFXWithOptimizedAppearEffect2
								__framer__adjustPosition={false}
								__framer__offset={0}
								__framer__parallaxTransformEnabled={true}
								__framer__speed={80}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation22}
								className={"framer-go13xt"}
								data-framer-appear-id={"go13xt"}
								fonts={["Inter"]}
								initial={animation32}
								layoutDependency={layoutDependency}
								layoutId={"LQKinzOGl"}
								optimized={true}
								style={{
									"--extracted-gdpscs":
										"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								transformTemplate={transformTemplate12}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.h1
										className={"framer-styles-preset-1jo3glk"}
										data-styles-preset={"enXnUuyN7"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(11, 11, 11)))",
										}}
									>
										{"Silence the noise."}
										<motion2.br />
										{"Find Your Peace."}
									</motion2.h1>
								</React2.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect2>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-x6ZFx.framer-1ftflqp, .framer-x6ZFx .framer-1ftflqp { display: block; }",
	".framer-x6ZFx.framer-jx0221 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 3092px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-x6ZFx .framer-1fxom9r-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; z-index: 1; }",
	".framer-x6ZFx .framer-yvj75c { flex: none; height: 31%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: -619px; width: 100%; z-index: 1; }",
	".framer-x6ZFx .framer-1jmvmzo { flex: none; height: 15%; left: 143px; overflow: visible; position: absolute; top: 158px; width: 23%; z-index: 1; }",
	".framer-x6ZFx .framer-b4yfvz { flex: none; height: auto; left: 50%; position: absolute; top: 274px; white-space: pre; width: auto; z-index: 1; }",
	".framer-x6ZFx .framer-163bi49 { flex: none; height: auto; left: 50%; position: absolute; top: 451px; white-space: pre; width: auto; z-index: 1; }",
	".framer-x6ZFx .framer-cc8q1p { flex: none; height: 15%; left: 1217px; overflow: visible; position: absolute; top: -42px; width: 28%; z-index: 1; }",
	".framer-x6ZFx .framer-1p5w3py { flex: none; height: 20%; left: 902px; overflow: visible; position: absolute; top: 377px; width: 50%; z-index: 1; }",
	".framer-x6ZFx .framer-f3edt2 { flex: none; height: 13%; left: -58px; overflow: visible; position: absolute; top: 461px; width: 34%; z-index: 1; }",
	".framer-x6ZFx .framer-7bm3kt { flex: none; height: 3226px; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(52.16688227684349% - 3226px / 2); width: 100%; z-index: 1; }",
	".framer-x6ZFx .framer-1kpk8dp { flex: none; height: 140px; left: calc(50.00000000000002% - 263px / 2); position: absolute; top: 1055px; width: 263px; }",
	".framer-x6ZFx .framer-go13xt { bottom: 775px; flex: none; height: auto; left: 50%; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-x6ZFx.framer-v-d7wzbt.framer-jx0221 { width: 1870px; }",
	".framer-x6ZFx.framer-v-d7wzbt .framer-7bm3kt, .framer-x6ZFx.framer-v-19556c .framer-7bm3kt { height: 104%; top: calc(52.16688227684349% - 104.33376455368692% / 2); }",
	".framer-x6ZFx.framer-v-d7wzbt .framer-1kpk8dp { height: 106px; top: 935px; }",
	".framer-x6ZFx.framer-v-19556c.framer-jx0221 { width: 1570px; }",
	".framer-x6ZFx.framer-v-19556c .framer-1kpk8dp { height: 94px; top: 1023px; }",
	".framer-x6ZFx.framer-v-1cu09ka.framer-jx0221 { height: 3134px; width: 810px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-yvj75c { height: 58%; top: -1360px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-1jmvmzo, .framer-x6ZFx.framer-v-1cu09ka .framer-cc8q1p { height: 14%; left: -292px; top: 89px; width: 540px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-b4yfvz { top: 256px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-163bi49 { top: 380px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-1p5w3py { height: 20%; left: 872px; top: -192px; width: 810px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-f3edt2 { height: 13%; left: 529px; top: 318px; width: 810px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-7bm3kt { height: 100%; top: 0px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-1kpk8dp { top: 1033px; }",
	".framer-x6ZFx.framer-v-1cu09ka .framer-go13xt { bottom: unset; height: 102px; top: 1991px; }",
	".framer-x6ZFx.framer-v-qtj6h4.framer-jx0221 { height: 3340px; width: 450px; }",
	".framer-x6ZFx.framer-v-qtj6h4 .framer-1fxom9r-container { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 1.1266467065868264); order: 0; }",
	".framer-x6ZFx.framer-v-qtj6h4 .framer-7bm3kt { bottom: 0px; height: 100%; order: 2; top: unset; }",
	".framer-x6ZFx.framer-v-qtj6h4 .framer-1kpk8dp { height: 85px; left: calc(53.33333333333336% - 179px / 2); top: 327px; width: 179px; }",
	...css3,
	...css,
	...css2,
];
var FramerzeRIJ9WaQ = withCSS2(Component2, css5, "framer-x6ZFx");
var stdin_default3 = FramerzeRIJ9WaQ;
FramerzeRIJ9WaQ.displayName = "Main";
FramerzeRIJ9WaQ.defaultProps = {
	height: 3092,
	width: 1440,
};
addPropertyControls(FramerzeRIJ9WaQ, {
	variant: {
		options: ["S48s0AycK", "oxU6qnjj1", "TKuC5YVdc", "hEtixOw54", "Cm2oxkrAC"],
		optionTitles: ["Desktop", "Variant", "Variant", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts2(
	FramerzeRIJ9WaQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BackgroundFonts,
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Cm2oxkrAC",
	md: "hEtixOw54",
	xl: "S48s0AycK",
	"2xl": "TKuC5YVdc",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders MainFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var main_default = ComponentWithRoot;
export { main_default as default };
