// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Normal' | 'Highlight' // Variant
 * plan?: string // Plan
 * price?: string // Price
 * feature1?: string // Feature 1
 * feature2?: string // Feature 2
 * feature3?: string // Feature 3
 * feature4?: string // Feature 4
 * buttonLabel?: string // Button Label
 * link?: string // Link
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6FB2SUDJ.js";
import { className, css, fonts } from "./chunks/chunk-PU7BSL5Q.js";
import {
	NullState,
	defaultEvents,
	useIconSelection,
} from "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:pricing-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Pricing-Card-YtOWp.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion3,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { useState, useEffect, useRef } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { motion } from "unframer";

// /:https://framer.com/m/phosphor-icons/House.js@0.0.53
var Component;
var House_default = (React4) => {
	if (!Component) {
		const weights = /* @__PURE__ */ new Map([
			[
				"bold",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M221.56,100.85,141.61,25.38l-.16-.15a19.93,19.93,0,0,0-26.91,0l-.17.15L34.44,100.85A20.07,20.07,0,0,0,28,115.55V208a20,20,0,0,0,20,20H96a20,20,0,0,0,20-20V164h24v44a20,20,0,0,0,20,20h48a20,20,0,0,0,20-20V115.55A20.07,20.07,0,0,0,221.56,100.85ZM204,204H164V160a20,20,0,0,0-20-20H112a20,20,0,0,0-20,20v44H52V117.28l76-71.75,76,71.75Z",
					}),
				),
			],
			[
				"duotone",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M216,115.54V208a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.54a8,8,0,0,1,2.62-5.92l80-75.54a8,8,0,0,1,10.77,0l80,75.54A8,8,0,0,1,216,115.54Z",
						opacity: "0.2",
					}),
					/* @__PURE__ */ React4.createElement("path", {
						d: "M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z",
					}),
				),
			],
			[
				"fill",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M224,115.55V208a16,16,0,0,1-16,16H168a16,16,0,0,1-16-16V168a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v40a16,16,0,0,1-16,16H48a16,16,0,0,1-16-16V115.55a16,16,0,0,1,5.17-11.78l80-75.48.11-.11a16,16,0,0,1,21.53,0,1.14,1.14,0,0,0,.11.11l80,75.48A16,16,0,0,1,224,115.55Z",
					}),
				),
			],
			[
				"light",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M217.47,105.24l-80-75.5-.09-.08a13.94,13.94,0,0,0-18.83,0l-.09.08-80,75.5A14,14,0,0,0,34,115.55V208a14,14,0,0,0,14,14H96a14,14,0,0,0,14-14V160a2,2,0,0,1,2-2h32a2,2,0,0,1,2,2v48a14,14,0,0,0,14,14h48a14,14,0,0,0,14-14V115.55A14,14,0,0,0,217.47,105.24ZM210,208a2,2,0,0,1-2,2H160a2,2,0,0,1-2-2V160a14,14,0,0,0-14-14H112a14,14,0,0,0-14,14v48a2,2,0,0,1-2,2H48a2,2,0,0,1-2-2V115.55a2,2,0,0,1,.65-1.48l.09-.08,79.94-75.48a2,2,0,0,1,2.63,0L209.26,114l.08.08a2,2,0,0,1,.66,1.48Z",
					}),
				),
			],
			[
				"regular",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z",
					}),
				),
			],
			[
				"thin",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M216.13,106.72,136.07,31.13a12,12,0,0,0-16.2.05L39.93,106.67A12,12,0,0,0,36,115.54V208a12,12,0,0,0,12,12H96a12,12,0,0,0,12-12V160a4,4,0,0,1,4-4h32a4,4,0,0,1,4,4v48a12,12,0,0,0,12,12h48a12,12,0,0,0,12-12V115.54A12,12,0,0,0,216.13,106.72ZM212,208a4,4,0,0,1-4,4H160a4,4,0,0,1-4-4V160a12,12,0,0,0-12-12H112a12,12,0,0,0-12,12v48a4,4,0,0,1-4,4H48a4,4,0,0,1-4-4V115.54a4.09,4.09,0,0,1,1.36-3L125.3,37.05a4,4,0,0,1,5.33,0l80.06,75.58a4,4,0,0,1,1.31,3Z",
					}),
				),
			],
		]);
		const House = React4.forwardRef((props, ref) =>
			/* @__PURE__ */ React4.createElement(
				"g",
				{
					ref,
					...props,
				},
				weights.get(props.weight),
			),
		);
		House.displayName = "House";
		Component = House;
	}
	return Component;
};

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
var iconKeys = [
	"AddressBook",
	"AirTrafficControl",
	"Airplane",
	"AirplaneInFlight",
	"AirplaneLanding",
	"AirplaneTakeoff",
	"AirplaneTilt",
	"Airplay",
	"Alarm",
	"Alien",
	"AlignBottom",
	"AlignBottomSimple",
	"AlignCenterVertical",
	"AlignLeft",
	"AlignLeftSimple",
	"AlignRight",
	"AlignRightSimple",
	"AlignTop",
	"AlignTopSimple",
	"AmazonLogo",
	"Anchor",
	"AnchorSimple",
	"AndroidLogo",
	"AngularLogo",
	"Aperture",
	"AppStoreLogo",
	"AppWindow",
	"AppleLogo",
	"ApplePodcastsLogo",
	"Archive",
	"ArchiveBox",
	"ArchiveTray",
	"Armchair",
	"ArrowArcLeft",
	"ArrowArcRight",
	"ArrowBendDownLeft",
	"ArrowBendDownRight",
	"ArrowBendLeftDown",
	"ArrowBendLeftUp",
	"ArrowBendRightDown",
	"ArrowBendRightUp",
	"ArrowBendUpLeft",
	"ArrowBendUpRight",
	"ArrowCircleDown",
	"ArrowCircleDownLeft",
	"ArrowCircleDownRight",
	"ArrowCircleLeft",
	"ArrowCircleRight",
	"ArrowCircleUp",
	"ArrowCircleUpLeft",
	"ArrowCircleUpRight",
	"ArrowClockwise",
	"ArrowDown",
	"ArrowDownLeft",
	"ArrowDownRight",
	"ArrowElbowDownLeft",
	"ArrowElbowDownRight",
	"ArrowElbowLeft",
	"ArrowElbowLeftDown",
	"ArrowElbowLeftUp",
	"ArrowElbowRight",
	"ArrowElbowRightDown",
	"ArrowElbowRightUp",
	"ArrowElbowUpLeft",
	"ArrowElbowUpRight",
	"ArrowFatDown",
	"ArrowFatLeft",
	"ArrowFatLineDown",
	"ArrowFatLineLeft",
	"ArrowFatLineRight",
	"ArrowFatLineUp",
	"ArrowFatLinesDown",
	"ArrowFatLinesLeft",
	"ArrowFatLinesRight",
	"ArrowFatLinesUp",
	"ArrowFatRight",
	"ArrowFatUp",
	"ArrowLeft",
	"ArrowLineDown",
	"ArrowLineDownLeft",
	"ArrowLineDownRight",
	"ArrowLineLeft",
	"ArrowLineRight",
	"ArrowLineUp",
	"ArrowLineUpLeft",
	"ArrowLineUpRight",
	"ArrowRight",
	"ArrowSquareDown",
	"ArrowSquareDownLeft",
	"ArrowSquareDownRight",
	"ArrowSquareIn",
	"ArrowSquareLeft",
	"ArrowSquareOut",
	"ArrowSquareRight",
	"ArrowSquareUp",
	"ArrowSquareUpLeft",
	"ArrowSquareUpRight",
	"ArrowUDownLeft",
	"ArrowUDownRight",
	"ArrowULeftDown",
	"ArrowULeftUp",
	"ArrowURightDown",
	"ArrowURightUp",
	"ArrowUUpLeft",
	"ArrowUUpRight",
	"ArrowUp",
	"ArrowUpLeft",
	"ArrowUpRight",
	"ArrowsClockwise",
	"ArrowsDownUp",
	"ArrowsHorizontal",
	"ArrowsIn",
	"ArrowsInCardinal",
	"ArrowsInLineVertical",
	"ArrowsInSimple",
	"ArrowsLeftRight",
	"ArrowsMerge",
	"ArrowsOut",
	"ArrowsOutCardinal",
	"ArrowsOutSimple",
	"ArrowsSplit",
	"ArrowsVertical",
	"Article",
	"ArticleMedium",
	"ArticleNyTimes",
	"Asterisk",
	"AsteriskSimple",
	"At",
	"Atom",
	"Baby",
	"Backpack",
	"Backspace",
	"Bag",
	"BagSimple",
	"Balloon",
	"Bandaids",
	"Bank",
	"Barbell",
	"Barcode",
	"Barricade",
	"Baseball",
	"BaseballCap",
	"Basket",
	"Basketball",
	"Bathtub",
	"BatteryCharging",
	"BatteryEmpty",
	"BatteryFull",
	"BatteryHigh",
	"BatteryLow",
	"BatteryMedium",
	"BatteryPlus",
	"BatteryPlusVertical",
	"BatteryVerticalEmpty",
	"BatteryVerticalFull",
	"BatteryVerticalHigh",
	"BatteryVerticalLow",
	"BatteryWarning",
	"Bed",
	"BeerBottle",
	"BeerStein",
	"BehanceLogo",
	"Bell",
	"BellRinging",
	"BellSimple",
	"BellSimpleRinging",
	"BellSimpleSlash",
	"BellSimpleZ",
	"BellSlash",
	"BellZ",
	"BezierCurve",
	"Bicycle",
	"Binoculars",
	"Bird",
	"Bluetooth",
	"BluetoothConnected",
	"BluetoothSlash",
	"BluetoothX",
	"Boat",
	"Bone",
	"Book",
	"BookBookmark",
	"BookOpen",
	"BookOpenText",
	"Bookmark",
	"BookmarkSimple",
	"Bookmarks",
	"BookmarksSimple",
	"Books",
	"Boot",
	"BoundingBox",
	"BowlFood",
	"BracketsAngle",
	"BracketsCurly",
	"BracketsRound",
	"BracketsSquare",
	"Brain",
	"Brandy",
	"Bridge",
	"Briefcase",
	"BriefcaseMetal",
	"Broadcast",
	"Broom",
	"Browser",
	"Browsers",
	"Bug",
	"BugBeetle",
	"BugDroid",
	"Buildings",
	"Bus",
	"Butterfly",
	"Cactus",
	"Cake",
	"Calculator",
	"Calendar",
	"CalendarBlank",
	"CalendarCheck",
	"CalendarPlus",
	"CalendarX",
	"CallBell",
	"Camera",
	"CameraPlus",
	"CameraRotate",
	"CameraSlash",
	"Campfire",
	"Car",
	"CarProfile",
	"CarSimple",
	"Cardholder",
	"Cards",
	"CaretCircleDoubleUp",
	"CaretCircleDown",
	"CaretCircleLeft",
	"CaretCircleRight",
	"CaretCircleUp",
	"CaretCircleUpDown",
	"CaretDoubleDown",
	"CaretDoubleLeft",
	"CaretDoubleRight",
	"CaretDoubleUp",
	"CaretDown",
	"CaretLeft",
	"CaretRight",
	"CaretUp",
	"CaretUpDown",
	"Carrot",
	"CassetteTape",
	"CastleTurret",
	"Cat",
	"CellSignalFull",
	"CellSignalHigh",
	"CellSignalLow",
	"CellSignalMedium",
	"CellSignalNone",
	"CellSignalSlash",
	"CellSignalX",
	"Certificate",
	"Chair",
	"Chalkboard",
	"ChalkboardSimple",
	"ChalkboardTeacher",
	"Champagne",
	"ChargingStation",
	"ChartBar",
	"ChartBarHorizontal",
	"ChartDonut",
	"ChartLine",
	"ChartLineDown",
	"ChartLineUp",
	"ChartPie",
	"ChartPieSlice",
	"ChartPolar",
	"ChartScatter",
	"Chat",
	"ChatCentered",
	"ChatCenteredDots",
	"ChatCenteredText",
	"ChatCircle",
	"ChatCircleDots",
	"ChatCircleText",
	"ChatDots",
	"ChatTeardrop",
	"ChatTeardropDots",
	"ChatTeardropText",
	"ChatText",
	"Chats",
	"ChatsCircle",
	"ChatsTeardrop",
	"Check",
	"CheckCircle",
	"CheckFat",
	"CheckSquare",
	"CheckSquareOffset",
	"Checks",
	"Church",
	"Circle",
	"CircleDashed",
	"CircleHalf",
	"CircleHalfTilt",
	"CircleNotch",
	"CirclesFour",
	"CirclesThree",
	"CirclesThreePlus",
	"Circuitry",
	"Clipboard",
	"ClipboardText",
	"Clock",
	"ClockAfternoon",
	"ClockClockwise",
	"ClockCounterClockwise",
	"ClockCountdown",
	"ClosedCaptioning",
	"Cloud",
	"CloudArrowDown",
	"CloudArrowUp",
	"CloudCheck",
	"CloudFog",
	"CloudLightning",
	"CloudMoon",
	"CloudRain",
	"CloudSlash",
	"CloudSnow",
	"CloudSun",
	"CloudWarning",
	"CloudX",
	"Club",
	"CoatHanger",
	"CodaLogo",
	"Code",
	"CodeBlock",
	"CodeSimple",
	"CodepenLogo",
	"CodesandboxLogo",
	"Coffee",
	"Coin",
	"CoinVertical",
	"Coins",
	"Columns",
	"Command",
	"Compass",
	"CompassTool",
	"ComputerTower",
	"Confetti",
	"ContactlessPayment",
	"Control",
	"Cookie",
	"CookingPot",
	"Copy",
	"CopySimple",
	"Copyleft",
	"Copyright",
	"CornersIn",
	"CornersOut",
	"Couch",
	"Cpu",
	"CreditCard",
	"Crop",
	"Cross",
	"Crosshair",
	"CrosshairSimple",
	"Crown",
	"CrownSimple",
	"Cube",
	"CubeFocus",
	"CubeTransparent",
	"CurrencyBtc",
	"CurrencyCircleDollar",
	"CurrencyCny",
	"CurrencyDollar",
	"CurrencyDollarSimple",
	"CurrencyEth",
	"CurrencyEur",
	"CurrencyGbp",
	"CurrencyInr",
	"CurrencyJpy",
	"CurrencyKrw",
	"CurrencyKzt",
	"CurrencyNgn",
	"CurrencyRub",
	"Cursor",
	"CursorClick",
	"CursorText",
	"Cylinder",
	"Database",
	"Desktop",
	"DesktopTower",
	"Detective",
	"DevToLogo",
	"DeviceMobile",
	"DeviceMobileCamera",
	"DeviceMobileSpeaker",
	"DeviceTablet",
	"DeviceTabletCamera",
	"DeviceTabletSpeaker",
	"Devices",
	"Diamond",
	"DiamondsFour",
	"DiceFive",
	"DiceFour",
	"DiceOne",
	"DiceSix",
	"DiceThree",
	"DiceTwo",
	"Disc",
	"DiscordLogo",
	"Divide",
	"Dna",
	"Dog",
	"Door",
	"DoorOpen",
	"Dot",
	"DotOutline",
	"DotsNine",
	"DotsSix",
	"DotsSixVertical",
	"DotsThree",
	"DotsThreeCircle",
	"DotsThreeOutline",
	"DotsThreeVertical",
	"Download",
	"DownloadSimple",
	"Dress",
	"DribbbleLogo",
	"Drop",
	"DropHalf",
	"DropHalfBottom",
	"DropboxLogo",
	"Ear",
	"EarSlash",
	"Egg",
	"EggCrack",
	"Eject",
	"EjectSimple",
	"Elevator",
	"Engine",
	"Envelope",
	"EnvelopeOpen",
	"EnvelopeSimple",
	"EnvelopeSimpleOpen",
	"Equalizer",
	"Equals",
	"Eraser",
	"EscalatorDown",
	"EscalatorUp",
	"Exam",
	"Exclude",
	"ExcludeSquare",
	"Export",
	"Eye",
	"EyeClosed",
	"EyeSlash",
	"Eyedropper",
	"EyedropperSample",
	"Eyeglasses",
	"FaceMask",
	"FacebookLogo",
	"Factory",
	"Faders",
	"FadersHorizontal",
	"Fan",
	"FastForward",
	"FastForwardCircle",
	"Feather",
	"FigmaLogo",
	"File",
	"FileArchive",
	"FileArrowDown",
	"FileArrowUp",
	"FileAudio",
	"FileCloud",
	"FileCode",
	"FileCss",
	"FileCsv",
	"FileDashed",
	"FileDoc",
	"FileHtml",
	"FileImage",
	"FileJpg",
	"FileJs",
	"FileJsx",
	"FileLock",
	"FileMagnifyingGlass",
	"FileMinus",
	"FilePdf",
	"FilePlus",
	"FilePng",
	"FilePpt",
	"FileRs",
	"FileSql",
	"FileSvg",
	"FileText",
	"FileTs",
	"FileTsx",
	"FileVideo",
	"FileVue",
	"FileX",
	"FileXls",
	"FileZip",
	"Files",
	"FilmReel",
	"FilmScript",
	"FilmSlate",
	"FilmStrip",
	"Fingerprint",
	"FingerprintSimple",
	"FinnTheHuman",
	"Fire",
	"FireExtinguisher",
	"FireSimple",
	"FirstAid",
	"FirstAidKit",
	"Fish",
	"FishSimple",
	"Flag",
	"FlagBanner",
	"FlagCheckered",
	"FlagPennant",
	"Flame",
	"Flashlight",
	"Flask",
	"FloppyDisk",
	"FloppyDiskBack",
	"FlowArrow",
	"Flower",
	"FlowerLotus",
	"FlowerTulip",
	"FlyingSaucer",
	"Folder",
	"FolderDashed",
	"FolderLock",
	"FolderMinus",
	"FolderNotch",
	"FolderNotchMinus",
	"FolderNotchOpen",
	"FolderNotchPlus",
	"FolderOpen",
	"FolderPlus",
	"FolderSimple",
	"FolderSimpleDashed",
	"FolderSimpleLock",
	"FolderSimpleMinus",
	"FolderSimplePlus",
	"FolderSimpleStar",
	"FolderSimpleUser",
	"FolderStar",
	"FolderUser",
	"Folders",
	"Football",
	"Footprints",
	"ForkKnife",
	"FrameCorners",
	"FramerLogo",
	"Function",
	"Funnel",
	"FunnelSimple",
	"GameController",
	"Garage",
	"GasCan",
	"GasPump",
	"Gauge",
	"Gavel",
	"Gear",
	"GearFine",
	"GearSix",
	"GenderFemale",
	"GenderIntersex",
	"GenderMale",
	"GenderNeuter",
	"GenderNonbinary",
	"GenderTransgender",
	"Ghost",
	"Gif",
	"Gift",
	"GitBranch",
	"GitCommit",
	"GitDiff",
	"GitFork",
	"GitMerge",
	"GitPullRequest",
	"GithubLogo",
	"GitlabLogo",
	"GitlabLogoSimple",
	"Globe",
	"GlobeHemisphereEast",
	"GlobeHemisphereWest",
	"GlobeSimple",
	"GlobeStand",
	"Goggles",
	"GoodreadsLogo",
	"GoogleCardboardLogo",
	"GoogleChromeLogo",
	"GoogleDriveLogo",
	"GoogleLogo",
	"GooglePhotosLogo",
	"GooglePlayLogo",
	"GooglePodcastsLogo",
	"Gradient",
	"GraduationCap",
	"Grains",
	"GrainsSlash",
	"Graph",
	"GridFour",
	"GridNine",
	"Guitar",
	"Hamburger",
	"Hammer",
	"Hand",
	"HandCoins",
	"HandEye",
	"HandFist",
	"HandGrabbing",
	"HandHeart",
	"HandPalm",
	"HandPointing",
	"HandSoap",
	"HandSwipeLeft",
	"HandSwipeRight",
	"HandTap",
	"HandWaving",
	"Handbag",
	"HandbagSimple",
	"HandsClapping",
	"HandsPraying",
	"Handshake",
	"HardDrive",
	"HardDrives",
	"Hash",
	"HashStraight",
	"Headlights",
	"Headphones",
	"Headset",
	"Heart",
	"HeartBreak",
	"HeartHalf",
	"HeartStraight",
	"HeartStraightBreak",
	"Heartbeat",
	"Hexagon",
	"HighHeel",
	"HighlighterCircle",
	"Hoodie",
	"Horse",
	"Hourglass",
	"HourglassHigh",
	"HourglassLow",
	"HourglassMedium",
	"HourglassSimple",
	"HourglassSimpleHigh",
	"HourglassSimpleLow",
	"House",
	"HouseLine",
	"HouseSimple",
	"IceCream",
	"IdentificationBadge",
	"IdentificationCard",
	"Image",
	"ImageSquare",
	"Images",
	"ImagesSquare",
	"Infinity",
	"Info",
	"InstagramLogo",
	"Intersect",
	"IntersectSquare",
	"IntersectThree",
	"Jeep",
	"Kanban",
	"Key",
	"KeyReturn",
	"Keyboard",
	"Keyhole",
	"Knife",
	"Ladder",
	"LadderSimple",
	"Lamp",
	"Laptop",
	"Layout",
	"Leaf",
	"Lifebuoy",
	"Lightbulb",
	"LightbulbFilament",
	"Lighthouse",
	"Lightning",
	"LightningA",
	"LightningSlash",
	"LineSegment",
	"LineSegments",
	"Link",
	"LinkBreak",
	"LinkSimple",
	"LinkSimpleBreak",
	"LinkSimpleHorizontal",
	"LinkedinLogo",
	"LinuxLogo",
	"List",
	"ListBullets",
	"ListChecks",
	"ListDashes",
	"ListMagnifyingGlass",
	"ListNumbers",
	"ListPlus",
	"Lock",
	"LockKey",
	"LockKeyOpen",
	"LockLaminated",
	"LockLaminatedOpen",
	"LockOpen",
	"LockSimple",
	"LockSimpleOpen",
	"Lockers",
	"MagicWand",
	"Magnet",
	"MagnetStraight",
	"MagnifyingGlass",
	"MagnifyingGlassMinus",
	"MagnifyingGlassPlus",
	"MapPin",
	"MapPinLine",
	"MapTrifold",
	"MarkerCircle",
	"Martini",
	"MaskHappy",
	"MaskSad",
	"MathOperations",
	"Medal",
	"MedalMilitary",
	"MediumLogo",
	"Megaphone",
	"MegaphoneSimple",
	"MessengerLogo",
	"MetaLogo",
	"Metronome",
	"Microphone",
	"MicrophoneSlash",
	"MicrophoneStage",
	"MicrosoftExcelLogo",
	"MicrosoftOutlookLogo",
	"MicrosoftTeamsLogo",
	"MicrosoftWordLogo",
	"Minus",
	"MinusCircle",
	"MinusSquare",
	"Money",
	"Monitor",
	"MonitorPlay",
	"Moon",
	"MoonStars",
	"Moped",
	"MopedFront",
	"Mosque",
	"Motorcycle",
	"Mountains",
	"Mouse",
	"MouseSimple",
	"MusicNote",
	"MusicNoteSimple",
	"MusicNotes",
	"MusicNotesPlus",
	"MusicNotesSimple",
	"NavigationArrow",
	"Needle",
	"Newspaper",
	"NewspaperClipping",
	"Notches",
	"Note",
	"NoteBlank",
	"NotePencil",
	"Notebook",
	"Notepad",
	"Notification",
	"NotionLogo",
	"NumberCircleEight",
	"NumberCircleFive",
	"NumberCircleFour",
	"NumberCircleNine",
	"NumberCircleOne",
	"NumberCircleSeven",
	"NumberCircleSix",
	"NumberCircleThree",
	"NumberCircleTwo",
	"NumberCircleZero",
	"NumberEight",
	"NumberFive",
	"NumberFour",
	"NumberNine",
	"NumberOne",
	"NumberSeven",
	"NumberSix",
	"NumberSquareEight",
	"NumberSquareFive",
	"NumberSquareFour",
	"NumberSquareNine",
	"NumberSquareOne",
	"NumberSquareSeven",
	"NumberSquareSix",
	"NumberSquareThree",
	"NumberSquareTwo",
	"NumberSquareZero",
	"NumberThree",
	"NumberTwo",
	"NumberZero",
	"Nut",
	"NyTimesLogo",
	"Octagon",
	"OfficeChair",
	"Option",
	"OrangeSlice",
	"Package",
	"PaintBrush",
	"PaintBrushBroad",
	"PaintBrushHousehold",
	"PaintBucket",
	"PaintRoller",
	"Palette",
	"Pants",
	"PaperPlane",
	"PaperPlaneRight",
	"PaperPlaneTilt",
	"Paperclip",
	"PaperclipHorizontal",
	"Parachute",
	"Paragraph",
	"Parallelogram",
	"Park",
	"Password",
	"Path",
	"PatreonLogo",
	"Pause",
	"PauseCircle",
	"PawPrint",
	"PaypalLogo",
	"Peace",
	"Pen",
	"PenNib",
	"PenNibStraight",
	"Pencil",
	"PencilCircle",
	"PencilLine",
	"PencilSimple",
	"PencilSimpleLine",
	"PencilSimpleSlash",
	"PencilSlash",
	"Pentagram",
	"Pepper",
	"Percent",
	"Person",
	"PersonArmsSpread",
	"PersonSimple",
	"PersonSimpleBike",
	"PersonSimpleRun",
	"PersonSimpleThrow",
	"PersonSimpleWalk",
	"Perspective",
	"Phone",
	"PhoneCall",
	"PhoneDisconnect",
	"PhoneIncoming",
	"PhoneOutgoing",
	"PhonePlus",
	"PhoneSlash",
	"PhoneX",
	"PhosphorLogo",
	"Pi",
	"PianoKeys",
	"PictureInPicture",
	"PiggyBank",
	"Pill",
	"PinterestLogo",
	"Pinwheel",
	"Pizza",
	"Placeholder",
	"Planet",
	"Plant",
	"Play",
	"PlayCircle",
	"PlayPause",
	"Playlist",
	"Plug",
	"PlugCharging",
	"Plugs",
	"PlugsConnected",
	"Plus",
	"PlusCircle",
	"PlusMinus",
	"PlusSquare",
	"PokerChip",
	"PoliceCar",
	"Polygon",
	"Popcorn",
	"PottedPlant",
	"Power",
	"Prescription",
	"Presentation",
	"PresentationChart",
	"Printer",
	"Prohibit",
	"ProhibitInset",
	"ProjectorScreen",
	"ProjectorScreenChart",
	"Pulse",
	"PushPin",
	"PushPinSimple",
	"PushPinSimpleSlash",
	"PushPinSlash",
	"PuzzlePiece",
	"QrCode",
	"Question",
	"Queue",
	"Quotes",
	"Radical",
	"Radio",
	"RadioButton",
	"Radioactive",
	"Rainbow",
	"RainbowCloud",
	"ReadCvLogo",
	"Receipt",
	"ReceiptX",
	"Record",
	"Rectangle",
	"Recycle",
	"RedditLogo",
	"Repeat",
	"RepeatOnce",
	"Rewind",
	"RewindCircle",
	"RoadHorizon",
	"Robot",
	"Rocket",
	"RocketLaunch",
	"Rows",
	"Rss",
	"RssSimple",
	"Rug",
	"Ruler",
	"Scales",
	"Scan",
	"Scissors",
	"Scooter",
	"Screencast",
	"ScribbleLoop",
	"Scroll",
	"Seal",
	"SealCheck",
	"SealQuestion",
	"SealWarning",
	"Selection",
	"SelectionAll",
	"SelectionBackground",
	"SelectionForeground",
	"SelectionInverse",
	"SelectionPlus",
	"SelectionSlash",
	"Shapes",
	"Share",
	"ShareFat",
	"ShareNetwork",
	"Shield",
	"ShieldCheck",
	"ShieldCheckered",
	"ShieldChevron",
	"ShieldPlus",
	"ShieldSlash",
	"ShieldStar",
	"ShieldWarning",
	"ShirtFolded",
	"ShootingStar",
	"ShoppingBag",
	"ShoppingBagOpen",
	"ShoppingCart",
	"ShoppingCartSimple",
	"Shower",
	"Shrimp",
	"Shuffle",
	"ShuffleAngular",
	"ShuffleSimple",
	"Sidebar",
	"SidebarSimple",
	"Sigma",
	"SignIn",
	"SignOut",
	"Signature",
	"Signpost",
	"SimCard",
	"Siren",
	"SketchLogo",
	"SkipBack",
	"SkipBackCircle",
	"SkipForward",
	"SkipForwardCircle",
	"Skull",
	"SlackLogo",
	"Sliders",
	"SlidersHorizontal",
	"Slideshow",
	"Smiley",
	"SmileyAngry",
	"SmileyBlank",
	"SmileyMeh",
	"SmileyNervous",
	"SmileySad",
	"SmileySticker",
	"SmileyWink",
	"SmileyXEyes",
	"SnapchatLogo",
	"Sneaker",
	"SneakerMove",
	"Snowflake",
	"SoccerBall",
	"SortAscending",
	"SortDescending",
	"SoundcloudLogo",
	"Spade",
	"Sparkle",
	"SpeakerHifi",
	"SpeakerHigh",
	"SpeakerLow",
	"SpeakerNone",
	"SpeakerSimpleHigh",
	"SpeakerSimpleLow",
	"SpeakerSimpleNone",
	"SpeakerSimpleSlash",
	"SpeakerSimpleX",
	"SpeakerSlash",
	"SpeakerX",
	"Spinner",
	"SpinnerGap",
	"Spiral",
	"SplitHorizontal",
	"SplitVertical",
	"SpotifyLogo",
	"Square",
	"SquareHalf",
	"SquareHalfBottom",
	"SquareLogo",
	"SquareSplitVertical",
	"SquaresFour",
	"Stack",
	"StackOverflowLogo",
	"StackSimple",
	"Stairs",
	"Stamp",
	"Star",
	"StarAndCrescent",
	"StarFour",
	"StarHalf",
	"StarOfDavid",
	"SteeringWheel",
	"Steps",
	"Stethoscope",
	"Sticker",
	"Stool",
	"Stop",
	"StopCircle",
	"Storefront",
	"Strategy",
	"StripeLogo",
	"Student",
	"Subtitles",
	"Subtract",
	"SubtractSquare",
	"Suitcase",
	"SuitcaseRolling",
	"SuitcaseSimple",
	"Sun",
	"SunDim",
	"SunHorizon",
	"Sunglasses",
	"Swap",
	"Swatches",
	"SwimmingPool",
	"Sword",
	"Synagogue",
	"Syringe",
	"TShirt",
	"Table",
	"Tabs",
	"Tag",
	"TagChevron",
	"TagSimple",
	"Target",
	"Taxi",
	"TelegramLogo",
	"Television",
	"TelevisionSimple",
	"TennisBall",
	"Tent",
	"Terminal",
	"TerminalWindow",
	"TestTube",
	"TextAUnderline",
	"TextAa",
	"TextAlignCenter",
	"TextAlignJustify",
	"TextAlignLeft",
	"TextAlignRight",
	"TextB",
	"TextColumns",
	"TextH",
	"TextHFive",
	"TextHFour",
	"TextHOne",
	"TextHSix",
	"TextHThree",
	"TextHTwo",
	"TextIndent",
	"TextItalic",
	"TextOutdent",
	"TextStrikethrough",
	"TextT",
	"TextUnderline",
	"Textbox",
	"Thermometer",
	"ThermometerCold",
	"ThermometerHot",
	"ThermometerSimple",
	"ThumbsDown",
	"ThumbsUp",
	"Ticket",
	"TidalLogo",
	"TiktokLogo",
	"Timer",
	"Tipi",
	"ToggleLeft",
	"ToggleRight",
	"Toilet",
	"ToiletPaper",
	"Toolbox",
	"Tooth",
	"Tote",
	"ToteSimple",
	"Trademark",
	"TrademarkRegistered",
	"TrafficCone",
	"TrafficSign",
	"TrafficSignal",
	"Train",
	"TrainRegional",
	"TrainSimple",
	"Tram",
	"Translate",
	"Trash",
	"TrashSimple",
	"Tray",
	"Tree",
	"TreeEvergreen",
	"TreePalm",
	"TreeStructure",
	"TrendDown",
	"TrendUp",
	"Triangle",
	"Trophy",
	"Truck",
	"TwitchLogo",
	"TwitterLogo",
	"Umbrella",
	"UmbrellaSimple",
	"Unite",
	"UniteSquare",
	"Upload",
	"UploadSimple",
	"Usb",
	"User",
	"UserCircle",
	"UserCircleGear",
	"UserCircleMinus",
	"UserCirclePlus",
	"UserFocus",
	"UserGear",
	"UserList",
	"UserMinus",
	"UserPlus",
	"UserRectangle",
	"UserSquare",
	"UserSwitch",
	"Users",
	"UsersFour",
	"UsersThree",
	"Van",
	"Vault",
	"Vibrate",
	"Video",
	"VideoCamera",
	"VideoCameraSlash",
	"Vignette",
	"VinylRecord",
	"VirtualReality",
	"Virus",
	"Voicemail",
	"Volleyball",
	"Wall",
	"Wallet",
	"Warehouse",
	"Warning",
	"WarningCircle",
	"WarningDiamond",
	"WarningOctagon",
	"Watch",
	"WaveSawtooth",
	"WaveSine",
	"WaveSquare",
	"WaveTriangle",
	"Waveform",
	"Waves",
	"Webcam",
	"WebcamSlash",
	"WebhooksLogo",
	"WechatLogo",
	"WhatsappLogo",
	"Wheelchair",
	"WheelchairMotion",
	"WifiHigh",
	"WifiLow",
	"WifiMedium",
	"WifiNone",
	"WifiSlash",
	"WifiX",
	"Wind",
	"WindowsLogo",
	"Wine",
	"Wrench",
	"X",
	"XCircle",
	"XSquare",
	"YinYang",
	"YoutubeLogo",
];
var moduleBaseUrl = "https://framer.com/m/phosphor-icons/";
var weightOptions = ["thin", "light", "regular", "bold", "fill", "duotone"];
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		weight,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? House_default(React) : null,
	);
	async function importModule() {
		try {
			const version = "0.0.53";
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (isMounted.current) setSelectedIcon(module.default(React));
		} catch (err) {
			if (isMounted.current) setSelectedIcon(null);
		}
	}
	useEffect(() => {
		isMounted.current = true;
		importModule();
		return () => {
			isMounted.current = false;
		};
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<motion.div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<svg
					xmlns={"http://www.w3.org/2000/svg"}
					viewBox={"0 0 256 256"}
					style={{
						userSelect: "none",
						width: "100%",
						height: "100%",
						display: "inline-block",
						fill: color,
						color,
						flexShrink: 0,
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					focusable={"false"}
					color={color}
				>
					<SelectedIcon color={color} weight={weight} />
				</svg>
			) : (
				emptyState
			)}
		</motion.div>
	);
}
Icon.displayName = "Phosphor";
Icon.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "House",
	iconSearch: "House",
	color: "#66F",
	selectByList: true,
	weight: "regular",
	mirrored: false,
};
addPropertyControls(Icon, {
	selectByList: {
		type: ControlType.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType.Enum,
		options: iconKeys,
		defaultValue: Icon.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Phosphor site](https://phosphoricons.com/)",
	},
	iconSearch: {
		type: ControlType.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: Icon.defaultProps.color,
	},
	weight: {
		type: ControlType.Enum,
		title: "Weight",
		optionTitles: weightOptions.map(
			(piece) => piece.charAt(0).toUpperCase() + piece.slice(1),
		),
		options: weightOptions,
		defaultValue: Icon.defaultProps.weight,
	},
	mirrored: {
		type: ControlType.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon.defaultProps.mirrored,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/5um1NJ9XiPrJxoknV0TX/hkLs3HKSlIyaJSI6GalW/pvsY9sahF.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Satoshi-bold",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/jn4BtSPLlS0NDp1KiFAtFKiiY0o.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/g0c8vEViiXNlKAgI4Ymmk3Ig.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css3 = [
	'.framer-rPtjl .framer-styles-preset-19u61o0:not(.rich-text-wrapper), .framer-rPtjl .framer-styles-preset-19u61o0.rich-text-wrapper h5 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 13px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: 0.04em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
];
var className3 = "framer-rPtjl";

// /:https://framerusercontent.com/modules/a7Tm7mjv0bwIxiC2Fe0V/jhGPHUjI7uGM8Xb27P4C/kwsX1BESG.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var MotionAWithFX = withFX(motion2.a);
var serializationHash = "framer-M94za";
var variantClassNames = {
	iysLx_Db5: "framer-v-13x79so",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 24,
};
var transition1 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps = ({ fillColor, height, id, link, width, ...props }) => {
	return {
		...props,
		eqpI4VwwC: fillColor ?? props.eqpI4VwwC ?? "rgb(255, 255, 255)",
		IfiHLeERP: link ?? props.IfiHLeERP,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		eqpI4VwwC,
		IfiHLeERP,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "iysLx_Db5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<Link
						href={IfiHLeERP}
						motionChild={true}
						nodeId={"iysLx_Db5"}
						scopeId={"kwsX1BESG"}
						smoothScroll={true}
					>
						<MotionAWithFX
							{...restProps}
							{...gestureHandlers}
							__framer__animate={{
								transition: transition1,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={`${cx(scopingClassNames, "framer-13x79so", className4, classNames)} framer-18aeie2`}
							data-border={true}
							data-framer-name={"Primary /Filled"}
							layoutDependency={layoutDependency}
							layoutId={"iysLx_Db5"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(34, 34, 34)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: eqpI4VwwC,
								borderBottomLeftRadius: 187,
								borderBottomRightRadius: 187,
								borderTopLeftRadius: 187,
								borderTopRightRadius: 187,
								...style,
							}}
						/>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-M94za.framer-18aeie2, .framer-M94za .framer-18aeie2 { display: block; }",
	".framer-M94za.framer-13x79so { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 45px; min-width: 90px; overflow: hidden; padding: 12px 20px 12px 20px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	'.framer-M94za[data-border="true"]::after, .framer-M94za [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerkwsX1BESG = withCSS(Component2, css4, "framer-M94za");
var stdin_default = FramerkwsX1BESG;
FramerkwsX1BESG.displayName = "Button With Link";
FramerkwsX1BESG.defaultProps = {
	height: 45,
	width: 90,
};
addPropertyControls2(FramerkwsX1BESG, {
	eqpI4VwwC: {
		defaultValue: "rgb(255, 255, 255)",
		title: "Fill Color",
		type: ControlType2.Color,
	},
	IfiHLeERP: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts(
	FramerkwsX1BESG,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Pricing-Card-YtOWp.js
var PhosphorFonts = getFonts(Icon);
var ButtonWithLinkFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX2(motion3.div);
var enabledGestures = {
	t8wq8THZ_: {
		hover: true,
	},
	ZalR92_yj: {
		hover: true,
	},
};
var cycleOrder = ["ZalR92_yj", "t8wq8THZ_"];
var serializationHash2 = "framer-6HXJy";
var variantClassNames2 = {
	t8wq8THZ_: "framer-v-mhlpy8",
	ZalR92_yj: "framer-v-i89pzx",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 24,
};
var transition12 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition12,
	x: 0,
	y: 24,
};
var transition22 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion3.create(React3.Fragment);
var humanReadableVariantMap = {
	Highlight: "t8wq8THZ_",
	Normal: "ZalR92_yj",
};
var getProps2 = ({
	buttonLabel,
	feature1,
	feature2,
	feature3,
	feature4,
	height,
	id,
	link,
	plan,
	price,
	width,
	...props
}) => {
	return {
		...props,
		AIzwVVvGa: feature3 ?? props.AIzwVVvGa ?? "10 GB of storage",
		dSirMJIHS: link ?? props.dSirMJIHS,
		iH9HEC9Qh: price ?? props.iH9HEC9Qh ?? "$9 /month",
		mK1KqUXW9: buttonLabel ?? props.mK1KqUXW9 ?? "Get started",
		Nf7pip_ZT: feature1 ?? props.Nf7pip_ZT ?? "5 users",
		Ttzrhylhi: feature2 ?? props.Ttzrhylhi ?? "Basic AI analytics",
		UkdOBmpxZ: plan ?? props.UkdOBmpxZ ?? "Starter plan",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ZalR92_yj",
		YLDaFMGlo: feature4 ?? props.YLDaFMGlo ?? "Access to all core features",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		UkdOBmpxZ,
		iH9HEC9Qh,
		Nf7pip_ZT,
		Ttzrhylhi,
		AIzwVVvGa,
		YLDaFMGlo,
		mK1KqUXW9,
		dSirMJIHS,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "ZalR92_yj",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "t8wq8THZ_-hover") return true;
		if (baseVariant === "t8wq8THZ_") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition22}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition12,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation2}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-i89pzx",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Normal"}
						layoutDependency={layoutDependency}
						layoutId={"ZalR92_yj"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-01bbde25-05c9-4f10-9741-7a896669af2f, rgb(239, 241, 243))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-28233f29-4906-463c-bd8c-93fe564b6964, rgb(253, 253, 253))",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							boxShadow:
								"0px 0.6021873017743928px 1.8065619053231785px -1.25px rgba(0, 0, 0, 0.35995), 0px 2.288533303243457px 6.8655999097303715px -2.5px rgba(0, 0, 0, 0.31779), 0px 10px 30px -3.75px rgba(0, 0, 0, 0.125)",
							...style,
						}}
						variants={{
							t8wq8THZ_: {
								backgroundColor:
									"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))",
							},
						}}
						{...addPropertyOverrides(
							{
								"t8wq8THZ_-hover": {
									"data-framer-name": void 0,
								},
								"ZalR92_yj-hover": {
									"data-framer-name": void 0,
								},
								t8wq8THZ_: {
									"data-framer-name": "Highlight",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-1sitzqh"}
							data-framer-name={"BgBlur"}
							layoutDependency={layoutDependency}
							layoutId={"Dg65biWU8"}
							style={{
								background:
									'radial-gradient(94% 69% at 50% 100%, var(--token-de34b1db-c617-47fd-9a6d-ca7f94a49e32, rgb(255, 224, 224)) /* {"name":"Background/ Secondary"} */ 0%, rgba(241, 206, 247, 0) 100%)',
								opacity: 0.4,
							}}
							variants={{
								"t8wq8THZ_-hover": {
									opacity: 0.6,
								},
								"ZalR92_yj-hover": {
									opacity: 1,
								},
							}}
						/>
						{isDisplayed() && (
							<motion3.div
								className={"framer-d5zj7m"}
								data-framer-name={"BgBlur"}
								layoutDependency={layoutDependency}
								layoutId={"ucHaFWiz4"}
								style={{
									background:
										'radial-gradient(135% 135% at 89.3% 0%, var(--token-de34b1db-c617-47fd-9a6d-ca7f94a49e32, rgb(255, 224, 224)) /* {"name":"Background/ Secondary"} */ 0%, rgba(241, 206, 247, 0) 100%)',
									opacity: 0.75,
								}}
								variants={{
									"t8wq8THZ_-hover": {
										opacity: 0.93,
									},
								}}
							/>
						)}
						<motion3.div
							className={"framer-1vrnxza"}
							data-framer-name={"Plan + Pricing"}
							layoutDependency={layoutDependency}
							layoutId={"j8suaApcC"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-jafrry"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"D4ejC6fEs"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={UkdOBmpxZ}
								variants={{
									t8wq8THZ_: {
										"--extracted-1lwpl3i":
											"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										t8wq8THZ_: {
											children: (
												<React3.Fragment>
													<motion3.h5
														className={"framer-styles-preset-19u61o0"}
														data-styles-preset={"pvsY9sahF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
														}}
													>
														{"Starter plan"}
													</motion3.h5>
												</React3.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React3.Fragment>
									<motion3.h5
										className={"framer-styles-preset-19u61o0"}
										data-styles-preset={"pvsY9sahF"}
									>
										{"Starter plan"}
									</motion3.h5>
								</React3.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-15a7ii8"}
								fonts={["Inter", "Inter-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"Ee9sOdRNM"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={iH9HEC9Qh}
								variants={{
									t8wq8THZ_: {
										"--extracted-a0htzi":
											"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										t8wq8THZ_: {
											children: (
												<React3.Fragment>
													<motion3.h3
														className={"framer-styles-preset-1tsd54f"}
														data-styles-preset={"DhsVO3ura"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
														}}
													>
														<motion3.strong>{"$9 /month"}</motion3.strong>
													</motion3.h3>
												</React3.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React3.Fragment>
									<motion3.h3
										className={"framer-styles-preset-1tsd54f"}
										data-styles-preset={"DhsVO3ura"}
									>
										<motion3.strong>{"$9 /month"}</motion3.strong>
									</motion3.h3>
								</React3.Fragment>
							</RichText>
						</motion3.div>
						<motion3.div
							className={"framer-19ys6ub"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"Kmcal1pXK"}
						>
							<motion3.div
								className={"framer-pkulqd"}
								data-framer-name={"Feature"}
								layoutDependency={layoutDependency}
								layoutId={"gIDRPaPBN"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-10p8b86-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"Hs_7Dw9ke-container"}
										nodeId={"Hs_7Dw9ke"}
										rendersWithMotion={true}
										scopeId={"m8itcLOk6"}
									>
										<Icon
											color={
												"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"CheckCircle"}
											id={"Hs_7Dw9ke"}
											layoutId={"Hs_7Dw9ke"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													t8wq8THZ_: {
														color:
															"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-12onpsx"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"hg8Ta8DKO"}
									text={Nf7pip_ZT}
									variants={{
										t8wq8THZ_: {
											"--extracted-r6o4lv":
												"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											t8wq8THZ_: {
												children: (
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-1hj8z0a"}
															data-styles-preset={"UByHkDadJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
															}}
														>
															{"5 users"}
														</motion3.p>
													</React3.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
										>
											{"5 users"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
							</motion3.div>
							<motion3.div
								className={"framer-1oc882r"}
								data-framer-name={"Feature"}
								layoutDependency={layoutDependency}
								layoutId={"YXMRnzJ5z"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-dj79y7-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"kVJ8rN88B-container"}
										nodeId={"kVJ8rN88B"}
										rendersWithMotion={true}
										scopeId={"m8itcLOk6"}
									>
										<Icon
											color={
												"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"CheckCircle"}
											id={"kVJ8rN88B"}
											layoutId={"kVJ8rN88B"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													t8wq8THZ_: {
														color:
															"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1mspis3"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ikshas9pN"}
									text={Ttzrhylhi}
									variants={{
										t8wq8THZ_: {
											"--extracted-r6o4lv":
												"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											t8wq8THZ_: {
												children: (
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-1hj8z0a"}
															data-styles-preset={"UByHkDadJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
															}}
														>
															{"Basic AI analytics"}
														</motion3.p>
													</React3.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
										>
											{"Basic AI analytics"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
							</motion3.div>
							<motion3.div
								className={"framer-1tbj49b"}
								data-framer-name={"Feature"}
								layoutDependency={layoutDependency}
								layoutId={"k6m0lY5Oi"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1ashzfu-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"xR9aNfxc6-container"}
										nodeId={"xR9aNfxc6"}
										rendersWithMotion={true}
										scopeId={"m8itcLOk6"}
									>
										<Icon
											color={
												"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"CheckCircle"}
											id={"xR9aNfxc6"}
											layoutId={"xR9aNfxc6"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													t8wq8THZ_: {
														color:
															"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-najhmb"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"swaBReOUR"}
									text={AIzwVVvGa}
									variants={{
										t8wq8THZ_: {
											"--extracted-r6o4lv":
												"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											t8wq8THZ_: {
												children: (
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-1hj8z0a"}
															data-styles-preset={"UByHkDadJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
															}}
														>
															{"10 GB of storage"}
														</motion3.p>
													</React3.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
										>
											{"10 GB of storage"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
							</motion3.div>
							<motion3.div
								className={"framer-hdzt2u"}
								data-framer-name={"Feature"}
								layoutDependency={layoutDependency}
								layoutId={"xGUJJYb5D"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1vinl2q-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"L0ZPD3UfK-container"}
										nodeId={"L0ZPD3UfK"}
										rendersWithMotion={true}
										scopeId={"m8itcLOk6"}
									>
										<Icon
											color={
												"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"CheckCircle"}
											id={"L0ZPD3UfK"}
											layoutId={"L0ZPD3UfK"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													t8wq8THZ_: {
														color:
															"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1jo3tjs"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"REmIrhoY_"}
									text={YLDaFMGlo}
									variants={{
										t8wq8THZ_: {
											"--extracted-r6o4lv":
												"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											t8wq8THZ_: {
												children: (
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-1hj8z0a"}
															data-styles-preset={"UByHkDadJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
															}}
														>
															{"Access to all core features"}
														</motion3.p>
													</React3.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
										>
											{"Access to all core features"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
							</motion3.div>
						</motion3.div>
						<ComponentViewportProvider
							height={52}
							width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
							y={(componentViewport?.y || 0) + 32 + 593.8}
						>
							<SmartComponentScopedContainer
								className={"framer-xdi6xg-container"}
								layoutDependency={layoutDependency}
								layoutId={"e_94kpqwM-container"}
								nodeId={"e_94kpqwM"}
								rendersWithMotion={true}
								scopeId={"m8itcLOk6"}
							>
								{_jsx3(stdin_default, {
									eFVapgzBc: mK1KqUXW9,
									eqpI4VwwC:
										"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))",
									height: "100%",
									hPmmUjgL0:
										"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
									id: "e_94kpqwM",
									IfiHLeERP: dSirMJIHS,
									layoutId: "e_94kpqwM",
									QurbhVBqJ: {
										borderColor:
											'var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0)) /* {"name":"Primary"} */',
										borderStyle: "solid",
										borderWidth: 2,
									},
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "iysLx_Db5",
									width: "100%",
									...addPropertyOverrides(
										{
											t8wq8THZ_: {
												eqpI4VwwC:
													"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
												hPmmUjgL0:
													"var(--token-fe8040e6-3344-44c0-bab9-226d490ba5f3, rgb(61, 0, 0))",
												QurbhVBqJ: {
													borderColor:
														'var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)) /* {"name":"Tertiary"} */',
													borderStyle: "solid",
													borderWidth: 2,
												},
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</MotionDivWithFX>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6HXJy.framer-1wpijwr, .framer-6HXJy .framer-1wpijwr { display: block; }",
	".framer-6HXJy.framer-i89pzx { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; min-height: 405px; overflow: hidden; padding: 32px; position: relative; width: 331px; will-change: var(--framer-will-change-override, transform); }",
	".framer-6HXJy .framer-1sitzqh { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	".framer-6HXJy .framer-d5zj7m { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-6HXJy .framer-1vrnxza { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6HXJy .framer-jafrry { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-6HXJy .framer-15a7ii8 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-6HXJy .framer-19ys6ub { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6HXJy .framer-pkulqd, .framer-6HXJy .framer-1oc882r, .framer-6HXJy .framer-1tbj49b, .framer-6HXJy .framer-hdzt2u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6HXJy .framer-10p8b86-container, .framer-6HXJy .framer-dj79y7-container, .framer-6HXJy .framer-1ashzfu-container, .framer-6HXJy .framer-1vinl2q-container { flex: none; height: 28px; position: relative; width: 28px; }",
	".framer-6HXJy .framer-12onpsx, .framer-6HXJy .framer-1mspis3, .framer-6HXJy .framer-najhmb, .framer-6HXJy .framer-1jo3tjs { -webkit-user-select: none; flex: 1 0 0px; height: auto; pointer-events: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-6HXJy .framer-xdi6xg-container { flex: none; height: 52px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6HXJy.framer-i89pzx, .framer-6HXJy .framer-1vrnxza, .framer-6HXJy .framer-19ys6ub, .framer-6HXJy .framer-pkulqd, .framer-6HXJy .framer-1oc882r, .framer-6HXJy .framer-1tbj49b, .framer-6HXJy .framer-hdzt2u { gap: 0px; } .framer-6HXJy.framer-i89pzx > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-6HXJy.framer-i89pzx > :first-child, .framer-6HXJy .framer-1vrnxza > :first-child, .framer-6HXJy .framer-19ys6ub > :first-child { margin-top: 0px; } .framer-6HXJy.framer-i89pzx > :last-child, .framer-6HXJy .framer-1vrnxza > :last-child, .framer-6HXJy .framer-19ys6ub > :last-child { margin-bottom: 0px; } .framer-6HXJy .framer-1vrnxza > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-6HXJy .framer-19ys6ub > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-6HXJy .framer-pkulqd > *, .framer-6HXJy .framer-1oc882r > *, .framer-6HXJy .framer-1tbj49b > *, .framer-6HXJy .framer-hdzt2u > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-6HXJy .framer-pkulqd > :first-child, .framer-6HXJy .framer-1oc882r > :first-child, .framer-6HXJy .framer-1tbj49b > :first-child, .framer-6HXJy .framer-hdzt2u > :first-child { margin-left: 0px; } .framer-6HXJy .framer-pkulqd > :last-child, .framer-6HXJy .framer-1oc882r > :last-child, .framer-6HXJy .framer-1tbj49b > :last-child, .framer-6HXJy .framer-hdzt2u > :last-child { margin-right: 0px; } }",
	".framer-6HXJy.framer-v-mhlpy8 .framer-1sitzqh, .framer-6HXJy.framer-v-mhlpy8.hover .framer-1sitzqh { z-index: unset; }",
	...css3,
	...css,
	...css2,
	'.framer-6HXJy[data-border="true"]::after, .framer-6HXJy [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerm8itcLOk6 = withCSS2(Component3, css5, "framer-6HXJy");
var stdin_default2 = Framerm8itcLOk6;
Framerm8itcLOk6.displayName = "Pricing Card";
Framerm8itcLOk6.defaultProps = {
	height: 406,
	width: 330.5,
};
addPropertyControls3(Framerm8itcLOk6, {
	variant: {
		options: ["ZalR92_yj", "t8wq8THZ_"],
		optionTitles: ["Normal", "Highlight"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	UkdOBmpxZ: {
		defaultValue: "Starter plan",
		displayTextArea: false,
		title: "Plan",
		type: ControlType3.String,
	},
	iH9HEC9Qh: {
		defaultValue: "$9 /month",
		displayTextArea: false,
		title: "Price",
		type: ControlType3.String,
	},
	Nf7pip_ZT: {
		defaultValue: "5 users",
		displayTextArea: false,
		title: "Feature 1",
		type: ControlType3.String,
	},
	Ttzrhylhi: {
		defaultValue: "Basic AI analytics",
		displayTextArea: false,
		title: "Feature 2",
		type: ControlType3.String,
	},
	AIzwVVvGa: {
		defaultValue: "10 GB of storage",
		displayTextArea: false,
		title: "Feature 3",
		type: ControlType3.String,
	},
	YLDaFMGlo: {
		defaultValue: "Access to all core features",
		displayTextArea: false,
		title: "Feature 4",
		type: ControlType3.String,
	},
	mK1KqUXW9: {
		defaultValue: "Get started",
		displayTextArea: false,
		title: "Button Label",
		type: ControlType3.String,
	},
	dSirMJIHS: {
		title: "Link",
		type: ControlType3.Link,
	},
});
addFonts2(
	Framerm8itcLOk6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...PhosphorFonts,
		...ButtonWithLinkFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pricing-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders PricingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var pricing_card_default = ComponentWithRoot;
export { pricing_card_default as default };
