// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 33572b55fb7efdaa "Filtr Landing page V1", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Normal' | 'Highlight' // Variant
 * testimonial?: string // Testimonial
 * name?: string // Name
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-JHEW7EWI.js";
import { className, css, fonts } from "./chunks/chunk-KHUWPRRZ.js";
import { routes } from "./chunks/chunk-T5SFBMCA.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/TestimonialCard-OmJ9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["zQvtq7QIk", "lTzyFC1zE"];
var serializationHash = "framer-sBOVd";
var variantClassNames = {
	lTzyFC1zE: "framer-v-1b599qb",
	zQvtq7QIk: "framer-v-1ymfgr2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Highlight: "lTzyFC1zE",
	Normal: "zQvtq7QIk",
};
var getProps = ({ height, id, image, name1, testimonial, width, ...props }) => {
	return {
		...props,
		d7G5ynI6Z: image ??
			props.d7G5ynI6Z ?? {
				src: "https://framerusercontent.com/images/0ecak76j68sYrYt3tUb8R8pBeWI.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/0ecak76j68sYrYt3tUb8R8pBeWI.jpg?scale-down-to=1024 819w,https://framerusercontent.com/images/0ecak76j68sYrYt3tUb8R8pBeWI.jpg?scale-down-to=2048 1638w,https://framerusercontent.com/images/0ecak76j68sYrYt3tUb8R8pBeWI.jpg?scale-down-to=4096 3276w,https://framerusercontent.com/images/0ecak76j68sYrYt3tUb8R8pBeWI.jpg 3846w",
			},
		pTIIiro11:
			testimonial ??
			props.pTIIiro11 ??
			'"Bloom has transformed the way I think about my life. Highly recommend!"',
		UcgXSZnPK: name1 ?? props.UcgXSZnPK ?? "Name",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zQvtq7QIk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		pTIIiro11,
		UcgXSZnPK,
		d7G5ynI6Z,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zQvtq7QIk",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "lTzyFC1zE") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "lTzyFC1zE") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ymfgr2",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Normal"}
						layoutDependency={layoutDependency}
						layoutId={"zQvtq7QIk"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-01bbde25-05c9-4f10-9741-7a896669af2f, rgb(239, 241, 243))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-28233f29-4906-463c-bd8c-93fe564b6964, rgb(253, 253, 253))",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							...style,
						}}
						{...addPropertyOverrides(
							{
								lTzyFC1zE: {
									"data-framer-name": "Highlight",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-13dm308"}
							data-framer-name={"BgBlur"}
							layoutDependency={layoutDependency}
							layoutId={"EuGI1hnT7"}
							style={{
								background:
									'radial-gradient(75% 50% at 50% 100%, var(--token-de34b1db-c617-47fd-9a6d-ca7f94a49e32, rgb(255, 224, 224)) /* {"name":"Secondary"} */ 0%, rgba(241, 206, 247, 0) 100%)',
								opacity: 0.4,
							}}
							variants={{
								lTzyFC1zE: {
									background:
										"linear-gradient(0deg, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0.7) 100%)",
									opacity: 1,
								},
							}}
						/>
						<motion.div
							className={"framer-j11f6j"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"XjbMak_2j"}
						>
							<motion.div
								className={"framer-j8kbl2"}
								layoutDependency={layoutDependency}
								layoutId={"RyQvzX611"}
							>
								{isDisplayed() && (
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													32 +
													(0 +
														0 +
														(((componentViewport?.height || 380) -
															64 -
															Math.max(
																0,
																((componentViewport?.height || 380) - 64 - 0) /
																	1,
															) *
																1) /
															1) *
															0) +
													0 +
													(0 +
														0 +
														((Math.max(
															0,
															((componentViewport?.height || 380) - 64 - 0) / 1,
														) *
															1 -
															0 -
															256) /
															1) *
															0) +
													0 +
													0,
											),
											...toResponsiveImage(d7G5ynI6Z),
											...{
												positionX: "center",
												positionY: "center",
											},
										}}
										className={"framer-4ofp4m"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"p3uP1cQUe"}
										style={{
											borderBottomLeftRadius: 698,
											borderBottomRightRadius: 698,
											borderTopLeftRadius: 698,
											borderTopRightRadius: 698,
										}}
									/>
								)}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-nkccf3"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"TcpvwRPrm"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={pTIIiro11}
									variants={{
										lTzyFC1zE: {
											"--extracted-a0htzi":
												"var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											lTzyFC1zE: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1tsd54f"}
															data-styles-preset={"DhsVO3ura"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-a79b86b8-c2a9-43b9-85bf-8ee058fb0bf6, rgb(255, 255, 255)))",
															}}
														>
															{
																'"Bloom has transformed the way I think about my life. Highly recommend!"'
															}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1hj8z0a"}
											data-styles-preset={"UByHkDadJ"}
										>
											{
												'"Bloom has transformed the way I think about my life. Highly recommend!"'
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-6azts2"}
								fonts={["Inter", "Inter-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"ZaUfSOqfD"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={UcgXSZnPK}
								variants={{
									lTzyFC1zE: {
										"--extracted-r6o4lv":
											"var(--token-33003885-6595-4fa2-a646-db5d9593a1e2, rgb(245, 251, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										lTzyFC1zE: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1hj8z0a"}
														data-styles-preset={"UByHkDadJ"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-33003885-6595-4fa2-a646-db5d9593a1e2, rgb(245, 251, 255)))",
														}}
													>
														<motion.strong>{"Name"}</motion.strong>
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1hj8z0a"}
										data-styles-preset={"UByHkDadJ"}
									>
										<motion.strong>{"Name"}</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						{isDisplayed1() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									...toResponsiveImage(d7G5ynI6Z),
								}}
								className={"framer-dl66wu"}
								data-framer-name={"BigImage"}
								layoutDependency={layoutDependency}
								layoutId={"XDr3lWObA"}
								{...addPropertyOverrides(
									{
										lTzyFC1zE: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0,
												),
												sizes: componentViewport?.width || "100vw",
												...toResponsiveImage(d7G5ynI6Z),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sBOVd.framer-1t4yx83, .framer-sBOVd .framer-1t4yx83 { display: block; }",
	".framer-sBOVd.framer-1ymfgr2 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 380px; justify-content: space-between; min-height: 380px; overflow: hidden; padding: 32px; position: relative; width: 378px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sBOVd .framer-13dm308 { bottom: -1px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	".framer-sBOVd .framer-j11f6j { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sBOVd .framer-j8kbl2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sBOVd .framer-4ofp4m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 52px; min-width: 52px; overflow: hidden; padding: 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-sBOVd .framer-nkccf3, .framer-sBOVd .framer-6azts2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-sBOVd .framer-dl66wu { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-sBOVd .framer-j8kbl2, .framer-sBOVd .framer-4ofp4m { gap: 0px; } .framer-sBOVd .framer-j8kbl2 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-sBOVd .framer-j8kbl2 > :first-child { margin-top: 0px; } .framer-sBOVd .framer-j8kbl2 > :last-child { margin-bottom: 0px; } .framer-sBOVd .framer-4ofp4m > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-sBOVd .framer-4ofp4m > :first-child { margin-left: 0px; } .framer-sBOVd .framer-4ofp4m > :last-child { margin-right: 0px; } }",
	".framer-sBOVd.framer-v-1b599qb.framer-1ymfgr2 { gap: 24px; justify-content: flex-end; padding: 0px; }",
	".framer-sBOVd.framer-v-1b599qb .framer-13dm308 { order: 1; z-index: 1; }",
	".framer-sBOVd.framer-v-1b599qb .framer-j11f6j { order: 2; padding: 32px; z-index: 2; }",
	".framer-sBOVd.framer-v-1b599qb .framer-j8kbl2 { z-index: 1; }",
	".framer-sBOVd.framer-v-1b599qb .framer-dl66wu { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-sBOVd.framer-v-1b599qb.framer-1ymfgr2 { gap: 0px; } .framer-sBOVd.framer-v-1b599qb.framer-1ymfgr2 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-sBOVd.framer-v-1b599qb.framer-1ymfgr2 > :first-child { margin-top: 0px; } .framer-sBOVd.framer-v-1b599qb.framer-1ymfgr2 > :last-child { margin-bottom: 0px; } }",
	...css,
	...css2,
	'.framer-sBOVd[data-border="true"]::after, .framer-sBOVd [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerYvgojCiku = withCSS(Component, css3, "framer-sBOVd");
var stdin_default = FramerYvgojCiku;
FramerYvgojCiku.displayName = "TestimonialCard";
FramerYvgojCiku.defaultProps = {
	height: 380,
	width: 378,
};
addPropertyControls(FramerYvgojCiku, {
	variant: {
		options: ["zQvtq7QIk", "lTzyFC1zE"],
		optionTitles: ["Normal", "Highlight"],
		title: "Variant",
		type: ControlType.Enum,
	},
	pTIIiro11: {
		defaultValue:
			'"Bloom has transformed the way I think about my life. Highly recommend!"',
		displayTextArea: true,
		title: "Testimonial",
		type: ControlType.String,
	},
	UcgXSZnPK: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	d7G5ynI6Z: {
		__defaultAssetReference:
			"data:framer/asset-reference,0ecak76j68sYrYt3tUb8R8pBeWI.jpg?originalFilename=photo-1560365163-3e8d64e762ef%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMnx8d29tYW4lMjBzbWlsaW5nfGVufDB8fHx8MTc0MDEzNjkzOHww%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerYvgojCiku,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"33572b55fb7efdaa249bc732b4d80938fb987e522fa46de7636e819dc1064156"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
